"""
Estate Grounds & Outbuildings Generator for BlendBuildingCreator.

Procedurally constructs detached outbuildings (stables, carriage barn, servant quarters /
steward lodge) and central courtyard focal points (ornate stone fountain, yard awnings)
for grand noble compounds and estates.

The detached outbuildings are not hand-modelled from raw boxes; they are generated by the
real main building pipeline (walls, floors, openings, roof) into a temporary mesh and then
transformed and merged into the estate mesh, so they read as genuine miniature buildings.
"""

import math
from mathutils import Vector, Matrix, Euler

from ..mesh_utils import (
    create_box, create_beveled_box, create_cylinder, create_cone, transform_faces
)
from ..materials import (
    MAT_INDEX_STONE, MAT_INDEX_CUT_STONE, MAT_INDEX_TIMBER,
    MAT_INDEX_TIMBER_FRAME, MAT_INDEX_WOOD, MAT_INDEX_SHINGLES,
    MAT_INDEX_PLASTER_EXT, MAT_INDEX_IRON, MAT_INDEX_GLASS,
    MAT_INDEX_FLOOR, MAT_INDEX_TARP, MAT_INDEX_WATER
)
from .furniture import build_barrel, build_crate, build_clay_pot


def _fx_ring_shell(bm, cx, cy, z0, z1, r_out0, r_out1, r_in0, r_in1, segments, mat,
                   close_bottom=True):
    """Smooth hollow conical ring (frustum shell): outer + inner walls, annulus caps.

    Used for the fountain's pool rim and upper bowl so the water can sit *inside*
    the stone with clearance instead of being a coplanar disc buried in a solid
    cylinder. ``segments`` should be high (40-48) to keep the silhouette round.
    """
    uv_layer = bm.loops.layers.uv.verify()
    outer0, outer1, inner0, inner1 = [], [], [], []
    for i in range(segments):
        a = 2.0 * math.pi * i / segments
        ca, sa = math.cos(a), math.sin(a)
        outer0.append(bm.verts.new((cx + r_out0 * ca, cy + r_out0 * sa, z0)))
        outer1.append(bm.verts.new((cx + r_out1 * ca, cy + r_out1 * sa, z1)))
        inner0.append(bm.verts.new((cx + r_in0 * ca, cy + r_in0 * sa, z0)))
        inner1.append(bm.verts.new((cx + r_in1 * ca, cy + r_in1 * sa, z1)))
    circ_out = 2.0 * math.pi * max(r_out0, 1e-4)
    circ_in = 2.0 * math.pi * max(r_in0, 1e-4)
    h = z1 - z0
    faces = []
    for i in range(segments):
        n = (i + 1) % segments
        # Outer wall (normal points radially outward).
        f = bm.faces.new([outer0[i], outer0[n], outer1[n], outer1[i]])
        f.material_index = mat
        u0 = circ_out * i / segments
        u1 = circ_out * (i + 1) / segments
        f.loops[0][uv_layer].uv = Vector((u0, 0.0))
        f.loops[1][uv_layer].uv = Vector((u1, 0.0))
        f.loops[2][uv_layer].uv = Vector((u1, h))
        f.loops[3][uv_layer].uv = Vector((u0, h))
        faces.append(f)
        # Inner wall (normal points inward, into the pool/bowl).
        f = bm.faces.new([inner0[n], inner0[i], inner1[i], inner1[n]])
        f.material_index = mat
        u0 = circ_in * i / segments
        u1 = circ_in * (i + 1) / segments
        f.loops[0][uv_layer].uv = Vector((u0, 0.0))
        f.loops[1][uv_layer].uv = Vector((u1, 0.0))
        f.loops[2][uv_layer].uv = Vector((u1, h))
        f.loops[3][uv_layer].uv = Vector((u0, h))
        faces.append(f)
        # Top annulus (planar projection, faces up).
        f = bm.faces.new([outer1[i], outer1[n], inner1[n], inner1[i]])
        f.material_index = mat
        for lp in f.loops:
            lp[uv_layer].uv = Vector((lp.vert.co.x, lp.vert.co.y))
        faces.append(f)
        # Bottom annulus (faces down).
        if close_bottom:
            f = bm.faces.new([outer0[i], inner0[i], inner0[n], outer0[n]])
            f.material_index = mat
            for lp in f.loops:
                lp[uv_layer].uv = Vector((lp.vert.co.x, lp.vert.co.y))
            faces.append(f)
    return faces


def build_estate_fountain(bm, pos=(0.0, -8.0, 0.0), tier='TIER_3'):
    """Smooth, round multi-tiered stone fountain for the central Cour d'Honneur.

    High-segment discs and true hollow rings keep the silhouette round; the pool and
    the upper catch-bowl are recessed so the water surface sits well below each rim
    with real clearance (no coplanar z-fighting between water and stone).
    """
    fx, fy, fz = pos
    big = tier == 'TIER_3'
    base_r = 3.6 if big else 2.8

    # 1. Stepped circular plinth (lower disc embeds slightly to avoid coincident planes).
    create_cylinder(bm, radius=base_r, height=0.22, segments=48,
                    location=(fx, fy, fz + 0.11), mat_index=MAT_INDEX_STONE)
    create_cylinder(bm, radius=base_r - 0.30, height=0.18, segments=48,
                    location=(fx, fy, fz + 0.30), mat_index=MAT_INDEX_CUT_STONE)
    z_plinth = fz + 0.39

    # 2. Pool: hollow ring rim with a flared coping, on a floor disc that stays just
    #    inside the rim (a hair of clearance so nothing is coplanar).
    basin_r = base_r - 0.45
    wall_t = 0.30
    pool_in = basin_r - wall_t
    create_cylinder(bm, radius=pool_in - 0.02, height=0.32, segments=48,
                    location=(fx, fy, z_plinth + 0.16), mat_index=MAT_INDEX_STONE)
    _fx_ring_shell(bm, fx, fy, z_plinth + 0.02, z_plinth + 0.66,
                   basin_r, basin_r + 0.07, pool_in, pool_in,
                   48, MAT_INDEX_CUT_STONE, close_bottom=True)
    # Recessed water surface, well below the coping (~0.3 m of freeboard).
    create_cylinder(bm, radius=pool_in - 0.04, height=0.015, segments=48,
                    location=(fx, fy, z_plinth + 0.36), mat_index=MAT_INDEX_WATER)
    z_floor_top = z_plinth + 0.32

    # 3. Central pedestal rising out of the pool.
    ped_r = 0.52 if big else 0.40
    ped_h = 1.45
    create_cylinder(bm, radius=ped_r + 0.16, height=0.26, segments=36,
                    location=(fx, fy, z_floor_top + 0.11), mat_index=MAT_INDEX_STONE)
    create_cylinder(bm, radius=ped_r, height=ped_h, segments=36,
                    location=(fx, fy, z_floor_top + 0.24 + ped_h * 0.5),
                    mat_index=MAT_INDEX_CUT_STONE)

    # 4. Upper catch-bowl: flared hollow ring with its own recessed water.
    bowl_z0 = z_floor_top + 0.24 + ped_h
    bowl_r = 1.15 if big else 0.90
    bowl_h = 0.50
    bowl_z1 = bowl_z0 + bowl_h
    _fx_ring_shell(bm, fx, fy, bowl_z0, bowl_z1,
                   ped_r + 0.02, bowl_r, ped_r - 0.10, bowl_r - 0.14,
                   40, MAT_INDEX_CUT_STONE, close_bottom=False)
    create_cylinder(bm, radius=bowl_r - 0.16, height=0.015, segments=40,
                    location=(fx, fy, bowl_z1 - 0.11), mat_index=MAT_INDEX_WATER)

    # 5. Central jet spire.
    create_cylinder(bm, radius=0.14, height=bowl_h + 0.30, segments=20,
                    location=(fx, fy, bowl_z0 + (bowl_h + 0.30) * 0.5),
                    mat_index=MAT_INDEX_CUT_STONE)
    finial_h = 0.80
    create_cone(bm, radius1=0.20, radius2=0.04, height=finial_h, segments=20,
                location=(fx, fy, bowl_z1 + 0.12 + finial_h * 0.5),
                mat_index=MAT_INDEX_CUT_STONE)
    create_cylinder(bm, radius=0.09, height=0.16, segments=12,
                    location=(fx, fy, bowl_z1 + 0.12 + finial_h + 0.06),
                    mat_index=MAT_INDEX_IRON)



# -----------------------------------------------------------------------------
# Reusable detached-building generation (reuses the main building pipeline)
# -----------------------------------------------------------------------------

# Estate/fotification toggles that must never be inherited by a generated outbuilding,
# otherwise every stable would recursively spawn its own stables and walls.
_OUTHOUSE_DISABLED = (
    'has_stable', 'has_servant_quarters', 'has_estate_fountain',
    'has_estate_guardhouse', 'has_estate_forge', 'has_estate_granary',
    'has_estate_chapel', 'has_estate_training_grounds',
    'has_palisade', 'has_curtain_wall', 'has_banners',
    'has_bastion_towers', 'has_military_props', 'has_mounted_shields',
    'has_gable_crest', 'has_side_annex', 'has_mini_wing',
    'has_balcony', 'has_corner_turrets', 'has_clock_tower',
    'has_veranda', 'has_trade_sign', 'has_flower_boxes',
    'has_outdoor_decor', 'has_well', 'has_arched_porch',
    'has_side_rampart', 'has_pillared_overhang',
)

_INHERITED = (
    'color_shingles', 'color_wall_ext', 'color_timber', 'color_stone',
    'color_floor', 'color_timber_frame', 'window_glow_strength',
    'include_door_leaves',
)


def _merge_generated_building(bm, base_props, overrides, pos=0.0, rot_z=0.0, preset_key=None):
    """Generate a detached building with the real pipeline and merge it into ``bm``.

    Builds a genuine miniature building using :func:`generate_building` (same walls,
    floors, openings, roof and materials as the main manor), bakes the placement
    transform into a temporary mesh, then appends it to the shared bmesh. The
    temp build prunes its slots to its own used set while the host mesh speaks
    canonical indices, so polygon indices are translated back to canonical (by
    material name) before merging — otherwise every merged outbuilding wears
    scrambled materials.

    When ``preset_key`` names a real style preset the outhouse is generated from that
    preset (e.g. the dedicated STABLE barn presets), with ``overrides`` then tuning the
    footprint and the placement.
    """
    import bpy
    from ..building import generate_building

    scene = bpy.data.scenes.new("_bbc_outhouse")
    mesh = bpy.data.meshes.new("_bbc_outhouse_mesh")
    obj = bpy.data.objects.new("_bbc_outhouse", mesh)
    try:
        op = scene.fantasy_building_settings
        op.auto_update = False
        op.building_archetype = 'NONE'
        _is_stable = bool(preset_key) and str(preset_key).startswith('STABLE')
        if preset_key:
            try:
                from ...presets import PRESETS, apply_preset
                if preset_key in PRESETS:
                    apply_preset(op, preset_key)
                    op.auto_update = False
                    # Working stable barns keep their STABLE archetype so the
                    # interior dresses as stalls + hay storage, never bedrooms.
                    op.building_archetype = 'STABLE' if _is_stable else 'NONE'
            except Exception:
                pass
        op.material_tier = getattr(base_props, 'material_tier', 'TIER_1')
        for _ck in _INHERITED:
            if hasattr(base_props, _ck) and hasattr(op, _ck):
                try:
                    setattr(op, _ck, getattr(base_props, _ck))
                except Exception:
                    pass
        for _fk in _OUTHOUSE_DISABLED:
            if hasattr(op, _fk):
                try:
                    setattr(op, _fk, False)
                except Exception:
                    pass
        for k, v in overrides.items():
            if hasattr(op, k):
                try:
                    setattr(op, k, v)
                except Exception:
                    pass

        generate_building(obj, op)

        # Translate the temp mesh's pruned slot indices back to canonical.
        try:
            from ..materials import canonical_slot_index
            _src_names = [m.name if m is not None else '' for m in obj.data.materials]
            _remap = {}
            for _si, _nm in enumerate(_src_names):
                _ci = canonical_slot_index(_nm)
                if _ci is not None:
                    _remap[_si] = _ci
            if _remap:
                for _poly in mesh.polygons:
                    if _poly.material_index in _remap:
                        _poly.material_index = _remap[_poly.material_index]
        except Exception:
            pass

        mat = (Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z'))
        mesh.transform(mat)
        bm.from_mesh(mesh)
    finally:
        bpy.data.objects.remove(obj, do_unlink=True)
        bpy.data.meshes.remove(mesh)
        bpy.data.scenes.remove(scene)


def _stable_key(tier):
    """Map a material tier ('TIER_1') to its STABLE preset key ('STABLE_T1')."""
    suffix = tier[-1] if tier else '1'
    return 'STABLE_T%s' % suffix


def _stable_dims(tier):
    """Footprint of the STABLE_<tier> preset, shared by the barn and the yard."""
    try:
        from ...presets import PRESETS
        s = PRESETS.get(_stable_key(tier), {}).get('settings', {})
        return s.get('width', 12.0), s.get('depth', 8.0)
    except Exception:
        return 12.0, 8.0


def build_stable(bm, props, pos=(-24.0, -10.0, 0.0), rot_z=0.0, tier='TIER_1',
                 width=None, depth=None):
    """Detached horse stable & carriage barn.

    The ``STABLE_<tier>`` preset is the baseline for the barn (walls, timber door, roof),
    optionally scaled up for grand estate compounds and castles. The working yard
    (stall row + paddock pen) matches the footprint dynamically.
    """
    overrides = {}
    if width is not None:
        overrides['width'] = width
    if depth is not None:
        overrides['depth'] = depth
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z,
                              preset_key=_stable_key(tier))
    bw, bd = _stable_dims(tier)
    if width is not None:
        bw = width
    if depth is not None:
        bd = depth
    t = Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z')
    _build_stable_yard(bm, t, bw, bd, tier)


def build_stable_yard_for_building(bm, props, ctx):
    """Build the stall row + paddock pen when the main building itself is a stable.

    Called from the archetype dispatch so a standalone STABLE preset gets the same
    yard as the estate stable, keeping the two paths identical.
    """
    tier = getattr(props, 'material_tier', 'TIER_1')
    bw, bd = _stable_dims(tier)
    _build_stable_yard(bm, Matrix.Identity(4), bw, bd, tier)


def _local_box(bm, t, size, loc, mat=MAT_INDEX_TIMBER, bevel=0.01, rot=(0.0, 0.0, 0.0)):
    """Place a beveled box in an outbuilding's rotated local frame."""
    return create_beveled_box(
        bm, size=size, location=loc, rotation=rot,
        transform_matrix=t, mat_index=mat, bevel_amount=bevel,
    )


def _build_stall_shelter(bm, t, x0, x1, y_back, depth, tier='TIER_1', stalls=3,
                         back_h=2.15, front_h=2.15):
    """Open-front timber stall row with a framed lean-to roof, opening toward -Y.

    Tier 1 gets a simple cloth/plank skin over a visible rafter frame (lumbermill
    feel); higher tiers get shingles. The shelter is a flat-roofed run-in shed, so
    the back wall, stall dividers and both end walls all share one height (nothing
    steps or pokes through); only the open front is framed by posts.
    """
    w = x1 - x0
    cx = (x0 + x1) * 0.5
    y_front = y_back - depth
    slope = back_h - front_h
    ang = math.atan2(slope, depth)
    rl = math.hypot(depth, slope)
    mid_y = y_back - depth * 0.5
    roof_mid_z = (back_h + front_h) * 0.5
    # One shared wall height for the back wall, dividers and ends: it clears the
    # roof underside everywhere the roof is lowest.
    wall_h = min(back_h, front_h) - 0.05

    # Plank back wall.
    plank_h = 0.24
    for i in range(int(wall_h / plank_h)):
        _local_box(bm, t, (w, 0.10, min(plank_h * 0.94, wall_h - i * plank_h)),
                   (cx, y_back, plank_h * (i + 0.5)), mat=MAT_INDEX_WOOD, bevel=0.008)
    # Front posts.
    for i in range(stalls + 1):
        px = x0 + w * i / stalls
        _local_box(bm, t, (0.16, 0.16, front_h), (px, y_front, front_h * 0.5),
                   mat=MAT_INDEX_TIMBER, bevel=0.012)
    # Solid divider walls between stalls, at the same height as the back wall.
    for i in range(1, stalls):
        px = x0 + w * i / stalls
        _local_box(bm, t, (0.10, depth, wall_h),
                   (px, y_back - depth * 0.5, wall_h * 0.5), mat=MAT_INDEX_WOOD, bevel=0.008)
    # Solid end walls close both flanks, matching the back wall height.
    for sx in (x0, x1):
        _local_box(bm, t, (0.10, depth, wall_h), (sx, y_back - depth * 0.5, wall_h * 0.5),
                   mat=MAT_INDEX_WOOD, bevel=0.008)

    # Rafter frame: front header on the posts and a back plate sitting on the wall.
    _local_box(bm, t, (w + 0.20, 0.14, 0.16), (cx, y_front, front_h + 0.02),
               mat=MAT_INDEX_TIMBER, bevel=0.008)
    _local_box(bm, t, (w + 0.20, 0.14, 0.16), (cx, y_back, wall_h + 0.08),
               mat=MAT_INDEX_TIMBER, bevel=0.008)
    for i in range(stalls + 1):
        rx = x0 + w * i / stalls
        _local_box(bm, t, (0.09, rl + 0.10, 0.09), (rx, mid_y, roof_mid_z + 0.10),
                   rot=(ang, 0.0, 0.0), mat=MAT_INDEX_TIMBER, bevel=0.006)

    # Roof slab, framed by bargeboards (sides) and a fascia board (front eave).
    roof_mat = MAT_INDEX_TARP if tier == 'TIER_1' else MAT_INDEX_SHINGLES
    roof_faces = _local_box(
        bm, t, (w + 0.34, rl + 0.30, 0.055),
        (cx, mid_y, roof_mid_z + 0.17), rot=(ang, 0.0, 0.0),
        mat=roof_mat, bevel=0.006)
    half_rl = rl * 0.5 + 0.15
    front_y = mid_y - half_rl * math.cos(ang)
    front_z = roof_mid_z + 0.17 - half_rl * math.sin(ang)
    _local_box(bm, t, (w + 0.40, 0.11, 0.16), (cx, front_y, front_z),
               rot=(ang, 0.0, 0.0), mat=MAT_INDEX_TIMBER, bevel=0.008)
    for s in (-1.0, 1.0):
        _local_box(bm, t, (0.12, rl + 0.30, 0.16),
                   (cx + s * (w * 0.5 + 0.17), mid_y, roof_mid_z + 0.16),
                   rot=(ang, 0.0, 0.0), mat=MAT_INDEX_TIMBER, bevel=0.008)

    # Match the main-roof shingle UVs (correct axis + 0.32 tiles/m) instead of the
    # default box mapping that leaves the tiles rotated and mis-scaled.
    if roof_mat == MAT_INDEX_SHINGLES:
        from ..roof.shingles import map_lean_to_shingle_uvs
        loc_world = t @ Vector((cx, mid_y, roof_mid_z + 0.17))
        rot_world = (t.to_3x3() @ Euler((ang, 0.0, 0.0), 'XYZ').to_matrix()).to_euler()
        map_lean_to_shingle_uvs(bm, roof_faces, loc_world, rot_world,
                                u_scale=0.32, v_scale=0.32)


def _build_pen_fence(bm, t, x0, x1, y0, y1, gate_w=1.7, post_h=1.25):
    """A rail-and-post paddock fence around the pen, with a gate gap on the -Y side."""
    def run(ax, ay, bx, by):
        length = math.hypot(bx - ax, by - ay)
        n = max(1, int(round(length / 1.6)))
        ang = math.atan2(by - ay, bx - ax)
        for i in range(n + 1):
            fx = ax + (bx - ax) * i / n
            fy = ay + (by - ay) * i / n
            _local_box(bm, t, (0.14, 0.14, post_h), (fx, fy, post_h * 0.5),
                       mat=MAT_INDEX_TIMBER, bevel=0.010)
        for rz in (0.50, 1.00):
            _local_box(bm, t, (length + 0.08, 0.08, 0.10),
                       ((ax + bx) * 0.5, (ay + by) * 0.5, rz),
                       rot=(0.0, 0.0, ang), mat=MAT_INDEX_TIMBER, bevel=0.006)

    run(x0, y0, x0, y1)                 # left flank
    run(x1, y0, x1, y1)                 # right flank
    # NOTE: no rail across the barn facade — it would block the carriage door.
    # Courtyard side split by a gate opening aligned with the barn door.
    gate_lo = -gate_w * 0.5
    gate_hi = gate_w * 0.5
    run(x0, y1, gate_lo, y1)
    run(gate_hi, y1, x1, y1)
    for gx in (gate_lo, gate_hi):
        _local_box(bm, t, (0.18, 0.18, post_h + 0.35), (gx, y1, (post_h + 0.35) * 0.5),
                   mat=MAT_INDEX_TIMBER, bevel=0.014)


def _build_stable_yard(bm, t, barn_w, barn_d, tier):
    """Compose the stable yard: fenced paddock plus a roofed open stall row.

    The pen is open along the barn facade (no rail in front of the carriage door)
    so horses and carts can be walked straight in through the gate.
    """
    barn_front = -barn_d * 0.5
    pen_d = 6.0
    pen_w = barn_w + 1.0
    x0, x1 = -pen_w * 0.5, pen_w * 0.5
    y0 = barn_front - 0.30            # barn side of the pen
    y1 = barn_front - pen_d           # courtyard side

    # Open stall row tucked along the left side of the pen, opening to the court.
    stall_w = min(pen_w * 0.5, 4.2)
    _build_stall_shelter(bm, t, x0 + 0.15, x0 + 0.15 + stall_w, y0 - 0.20, 3.0,
                         tier=tier, stalls=3)
    _build_pen_fence(bm, t, x0, x1, y0, y1)


def build_servant_quarters(bm, props, pos=(24.0, -10.0, 0.0), rot_z=0.0, tier='TIER_1',
                           width=12.0, depth=7.0, floors=2, floor_h=2.7):
    """Detached servant lodge / steward residence, generated with the main building pipeline."""
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.28,
        'has_cantilever': floors > 1,
        'overhang_mode': 'SECOND_FLOOR_ONLY',
        'cantilever_overhang': 0.22,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_height': 0.50,
        'ground_floor_stone': True,
        'has_ceiling_beams': False,
        'has_stairs': floors > 1,
        'stair_style': 'STRAIGHT',
        'has_front_door': True,
        'door_width': 1.35,
        'door_height': 2.25,
        'door_shape': 'AUTO',
        'door_angle': 0.0,
        'has_windows': True,
        'window_spacing': 2.4,
        'has_shutters': True,
        'shutter_state': 'OPEN',
        'has_timber_framing': True,
        'timber_diagonals': True,
        'roof_style': 'SWAY',
        'roof_orientation': 'LEFT_RIGHT',
        'roof_height': 2.6,
        'roof_overhang': 0.60,
        'has_roof_shingles': True,
        'has_dormers': tier in ('TIER_2', 'TIER_3'),
        'dormer_count': 2 if floors > 1 else 1,
        'dormer_sides': 'FRONT',
        'has_mini_wing': floors > 1 and tier in ('TIER_2', 'TIER_3'),
        'mini_wing_count': 1,
        'mini_wing_width': 2.0,
        'mini_wing_depth': 1.2,
        'has_chimney': True,
        'chimney_pos_x': 0.55,
        'chimney_pos_y': 0.0,
        'has_balcony': floors > 1,
        'balcony_side': 'FRONT',
        'balcony_width': 2.2,
        'balcony_depth': 1.1,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)


def build_guardhouse(bm, props, pos=(24.0, -28.0, 0.0), rot_z=0.0, tier='TIER_1',
                     width=10.5, depth=6.5, floors=1, floor_h=2.8):
    """Detached gate guardhouse & watch lodge."""
    is_t3 = tier == 'TIER_3'
    is_t1 = tier == 'TIER_1'
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.30 if is_t3 else 0.28,
        'has_cantilever': floors > 1 and not is_t1,
        'overhang_mode': 'SECOND_FLOOR_ONLY',
        'cantilever_overhang': 0.24,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_type': 'WOOD' if is_t1 else 'STONE',
        'foundation_height': 0.55,
        'ground_floor_stone': not is_t1,
        'has_ceiling_beams': False,
        'has_stairs': floors > 1,
        'stair_style': 'STRAIGHT',
        'has_front_door': True,
        'door_width': 1.40,
        'door_height': 2.30,
        'door_shape': 'ARCHED' if not is_t1 else 'SQUARE',
        'door_angle': 0.0,
        'has_windows': True,
        'window_spacing': 2.4,
        'has_shutters': True,
        'shutter_state': 'OPEN',
        'has_timber_framing': not is_t1,
        'timber_diagonals': not is_t1,
        'roof_style': 'GABLE' if is_t3 else 'SWAY',
        'roof_orientation': 'LEFT_RIGHT',
        'roof_height': 2.7,
        'roof_overhang': 0.60,
        'has_roof_shingles': True,
        'has_dormers': floors > 1 or tier in ('TIER_2', 'TIER_3'),
        'dormer_count': 1,
        'dormer_sides': 'FRONT',
        'has_mini_wing': floors > 1 and tier in ('TIER_2', 'TIER_3'),
        'mini_wing_count': 1,
        'mini_wing_width': 2.0,
        'mini_wing_depth': 1.2,
        'has_chimney': True,
        'chimney_pos_x': 0.50,
        'chimney_pos_y': 0.0,
        'has_balcony': floors > 1,
        'balcony_side': 'FRONT',
        'balcony_width': 2.0,
        'balcony_depth': 1.1,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)
    try:
        from .military_props import build_weapon_rack
        t = Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z')
        rw_pos = t @ Vector((-width * 0.28, -depth * 0.5 - 0.75, 0.0))
        nrm = t.to_3x3() @ Vector((0.0, -1.0, 0.0))
        build_weapon_rack(bm, rw_pos.x, rw_pos.y, 0.0, normal=(nrm.x, nrm.y, 0.0))
    except Exception:
        pass


def build_estate_forge(bm, props, pos=(-24.0, -28.0, 0.0), rot_z=0.0, tier='TIER_1',
                       width=10.5, depth=6.5, floors=1, floor_h=2.8):
    """Detached estate armory & blacksmith forge."""
    is_t3 = tier == 'TIER_3'
    is_t1 = tier == 'TIER_1'
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.32 if is_t3 else 0.30,
        'has_cantilever': False,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_type': 'STONE',
        'foundation_height': 0.60,
        'ground_floor_stone': True,
        'has_ceiling_beams': False,
        'has_stairs': floors > 1,
        'stair_style': 'STRAIGHT',
        'has_front_door': True,
        'door_width': 1.60,
        'door_height': 2.40,
        'door_shape': 'SQUARE',
        'door_angle': 0.0,
        'has_windows': True,
        'window_spacing': 2.4,
        'has_shutters': True,
        'shutter_state': 'OPEN',
        'has_timber_framing': not is_t1,
        'timber_diagonals': not is_t1,
        'roof_style': 'SWAY',
        'roof_orientation': 'LEFT_RIGHT',
        'roof_height': 2.8,
        'roof_overhang': 0.65,
        'has_roof_shingles': True,
        'has_dormers': tier in ('TIER_2', 'TIER_3'),
        'dormer_count': 1,
        'dormer_sides': 'FRONT',
        'has_chimney': True,
        'chimney_pos_x': 0.70,
        'chimney_pos_y': 0.0,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)
    try:
        t = Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z')
        anv_loc = t @ Vector((width * 0.25, -depth * 0.5 - 1.25, 0.0))
        create_cylinder(bm, radius=0.34, height=0.58, segments=16,
                        location=(anv_loc.x, anv_loc.y, 0.29), mat_index=MAT_INDEX_TIMBER)
        ang_z = rot_z + 0.3
        create_beveled_box(bm, size=(0.58, 0.26, 0.28),
                           location=(anv_loc.x, anv_loc.y, 0.58 + 0.14),
                           rotation=(0.0, 0.0, ang_z),
                           mat_index=MAT_INDEX_IRON, bevel_amount=0.015)
        ax = math.cos(ang_z)
        ay = math.sin(ang_z)
        horn_pos = anv_loc + Vector((ax * 0.36, ay * 0.36, 0.58 + 0.14))
        create_cone(bm, radius1=0.09, radius2=0.015, height=0.22, segments=12,
                    location=horn_pos,
                    rotation=(0.0, 1.5708, ang_z),
                    mat_index=MAT_INDEX_IRON)
        tub_loc = t @ Vector((width * 0.25 + 1.10, -depth * 0.5 - 1.30, 0.0))
        build_barrel(bm, x=tub_loc.x, y=tub_loc.y, z_ground=0.0, radius=0.36, height=0.75)
        crate_loc = t @ Vector((width * 0.25 - 1.05, -depth * 0.5 - 1.20, 0.0))
        build_crate(bm, x=crate_loc.x, y=crate_loc.y, z_ground=0.0, size=0.60, height=0.52)
    except Exception:
        pass


def build_estate_granary(bm, props, pos=(-28.0, 8.0, 0.0), rot_z=0.0, tier='TIER_1',
                         width=9.5, depth=6.0, floors=1, floor_h=2.8):
    """Detached estate granary & provisions storehouse."""
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.28,
        'has_cantilever': False,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_type': 'WOOD',
        'foundation_height': 0.65,
        'ground_floor_stone': False,
        'has_ceiling_beams': False,
        'has_stairs': False,
        'has_front_door': True,
        'door_width': 1.60,
        'door_height': 2.35,
        'door_shape': 'SQUARE',
        'door_angle': 0.0,
        'has_windows': True,
        'window_spacing': 2.6,
        'has_shutters': True,
        'shutter_state': 'OPEN',
        'has_timber_framing': True,
        'timber_diagonals': True,
        'plank_direction': 'HORIZONTAL',
        'roof_style': 'SWAY',
        'roof_orientation': 'LEFT_RIGHT',
        'roof_height': 2.7,
        'roof_overhang': 0.70,
        'has_roof_shingles': True,
        'has_dormers': True,
        'dormer_count': 1,
        'dormer_sides': 'FRONT',
        'has_chimney': False,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)
    try:
        t = Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z')
        c1 = t @ Vector((-width * 0.30, -depth * 0.5 - 0.70, 0.0))
        build_crate(bm, x=c1.x, y=c1.y, z_ground=0.0, size=0.55, height=0.50)
        c2 = t @ Vector((-width * 0.30 + 0.60, -depth * 0.5 - 0.65, 0.0))
        build_barrel(bm, x=c2.x, y=c2.y, z_ground=0.0, radius=0.30, height=0.68)
    except Exception:
        pass


def build_estate_chapel(bm, props, pos=(28.0, 8.0, 0.0), rot_z=0.0, tier='TIER_3',
                        width=10.5, depth=6.5, floors=1, floor_h=3.6):
    """Detached estate chantry chapel & treasury (consecrated private sanctuary)."""
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.36,
        'has_cantilever': False,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_type': 'STONE',
        'foundation_height': 0.75,
        'ground_floor_stone': True,
        'has_ceiling_beams': True,
        'has_stairs': False,
        'has_front_door': True,
        'door_width': 1.60,
        'door_height': 2.70,
        'door_shape': 'ARCHED',
        'door_angle': 0.0,
        'has_windows': True,
        'window_spacing': 2.2,
        'has_shutters': False,
        'has_timber_framing': False,
        'roof_style': 'GABLE',
        'roof_orientation': 'LEFT_RIGHT',
        'roof_height': 3.4,
        'roof_overhang': 0.65,
        'has_roof_shingles': True,
        'has_dormers': False,
        'has_chimney': False,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)
    try:
        t = Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z')
        # Front arched stone bell-cote / sanctus bell turret over entrance gable
        z_ridge = 0.75 + floor_h + 3.4
        create_beveled_box(bm, size=(1.20, 0.45, 1.40),
                           location=(t @ Vector((0.0, 0.0, z_ridge + 0.70))),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_CUT_STONE, bevel_amount=0.03)
        create_cylinder(bm, radius=0.22, height=0.35, segments=16,
                        location=(t @ Vector((0.0, 0.0, z_ridge + 0.65))),
                        rotation=(1.5708, 0.0, rot_z),
                        mat_index=MAT_INDEX_IRON)
        # Stone steps leading to chapel arched entrance
        create_beveled_box(bm, size=(2.40, 0.85, 0.22),
                           location=(t @ Vector((0.0, -depth * 0.5 - 0.42, 0.11))),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_STONE, bevel_amount=0.02)
        create_beveled_box(bm, size=(2.10, 0.65, 0.22),
                           location=(t @ Vector((0.0, -depth * 0.5 - 0.25, 0.33))),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_CUT_STONE, bevel_amount=0.02)
    except Exception:
        pass

def build_tenement_building(bm, props, pos=(24.0, 10.0, 0.0), rot_z=0.0, tier='TIER_3',
                            width=24.0, depth=11.0, floors=3, floor_h=3.4):
    """Substantial multi-storey tenement block for castle servants, craftsmen, or garrison."""
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.34,
        'has_cantilever': floors > 1 and tier != 'TIER_1',
        'overhang_mode': 'SECOND_FLOOR_ONLY',
        'cantilever_overhang': 0.35,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_height': 0.70,
        'ground_floor_stone': True,
        'has_ceiling_beams': False,
        'has_stairs': floors > 1,
        'stair_style': 'STRAIGHT',
        'has_front_door': True,
        'door_width': 1.65,
        'door_height': 2.50,
        'door_shape': 'ARCHED' if tier == 'TIER_3' else 'AUTO',
        'has_windows': True,
        'window_spacing': 2.2,
        'has_shutters': True,
        'shutter_state': 'OPEN',
        'has_timber_framing': True,
        'timber_diagonals': True,
        'roof_style': 'SWAY',
        'roof_orientation': 'LEFT_RIGHT',
        'roof_height': 4.4,
        'roof_overhang': 0.75,
        'has_roof_shingles': True,
        'has_dormers': True,
        'dormer_count': 4,
        'dormer_sides': 'BOTH',
        'has_chimney': True,
        'chimney_pos_x': 0.65,
        'has_balcony': floors > 1,
        'balcony_side': 'FRONT',
        'balcony_width': 3.6,
        'balcony_depth': 1.3,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)



def build_retainer_house(bm, props, pos=(24.0, -10.0, 0.0), rot_z=0.0, tier='TIER_3',
                         width=15.5, depth=9.0, floors=2, floor_h=3.4, name="Castellan"):
    """Dignified upscale 2-storey manor residence for a key castle retainer (Castellan, High Steward, Chamberlain)."""
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.32,
        'has_cantilever': floors > 1 and tier != 'TIER_1',
        'overhang_mode': 'SECOND_FLOOR_ONLY',
        'cantilever_overhang': 0.30,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_height': 0.65,
        'ground_floor_stone': True,
        'has_ceiling_beams': True,
        'has_stairs': floors > 1,
        'stair_style': 'STRAIGHT',
        'has_front_door': True,
        'door_width': 1.60,
        'door_height': 2.50,
        'door_shape': 'ARCHED',
        'has_windows': True,
        'window_spacing': 2.5,
        'has_shutters': True,
        'shutter_state': 'OPEN',
        'has_timber_framing': True,
        'timber_diagonals': True,
        'roof_style': 'GABLE' if tier == 'TIER_3' else 'SWAY',
        'roof_orientation': 'LEFT_RIGHT',
        'roof_height': 3.4,
        'roof_overhang': 0.70,
        'has_roof_shingles': True,
        'has_dormers': True,
        'dormer_count': 2,
        'dormer_sides': 'FRONT',
        'has_chimney': True,
        'chimney_pos_x': 0.65,
        'has_balcony': True,
        'balcony_side': 'FRONT',
        'balcony_width': 3.0,
        'balcony_depth': 1.3,
        'has_mini_wing': True,
        'mini_wing_count': 1,
        'mini_wing_width': 2.2,
        'mini_wing_depth': 1.2,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)


def build_estate_training_grounds(bm, pos=(-30.0, -50.0, 0.0), rot_z=0.0, tier='TIER_3',
                                   width=32.0, depth=22.0):
    """Fortified courtyard military training grounds, archery drill yard, and sparring arena.

    Features:
    - Post-and-rail rustic timber palisade boundary (clean timber posts directly into earth, no stone plinths).
    - Front opening gate with proud heraldic round shields mounted on outer face with iron brackets.
    - Archery Range on the long side (back fence): exactly 2 traditional straw archery target butts on tripods
      with shooting line rail and arrow supply barrels.
    - Sparring Arena: dedicated 8.4m octagonal timber combat ring with corner timber posts, pyramid caps,
      double barrier rails, walk-in entrance opening, central rope-wrapped heavy sparring pell post,
      and 2 swivel combat training dummies.
    - Armory weapon rack stocked with polearms, halberds, spears, broadswords, and practice wasters.
    - Inward-facing spectator / drill timber benches overlooking both the sparring arena and archery range.
    - Armorer's supply crates, tool chest, water cooling trough, and provision barrels.
    - Lord Nasher's high heraldic standard pole flying cloth banner pennon.
    """
    from .military_props import build_archery_target, build_weapon_rack, build_training_dummy
    from .furniture import build_bench, build_crate, build_barrel
    from .shield import build_round_shield
    from .banner import build_banner_pole

    t = Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z')
    half_w = width * 0.5
    half_d = depth * 0.5

    # 1. Post-and-rail perimeter fencing (clean rustic timber, no stone plinths)
    post_spacing = 2.5
    n_posts_x = max(3, int(round(width / post_spacing)))
    step_x = width / n_posts_x
    n_posts_y = max(3, int(round(depth / post_spacing)))
    step_y = depth / n_posts_y

    fence_h = 1.15

    # Posts along Left and Right edges
    for sgn_x in (-1.0, 1.0):
        px_val = sgn_x * half_w
        for j in range(n_posts_y + 1):
            py_val = -half_d + j * step_y
            p_world = t @ Vector((px_val, py_val, 0.0))
            create_beveled_box(bm, size=(0.16, 0.16, fence_h),
                               location=(p_world.x, p_world.y, fence_h * 0.5),
                               rotation=(0.0, 0.0, rot_z),
                               mat_index=MAT_INDEX_TIMBER, bevel_amount=0.010)

        # Rails connecting posts along Y
        rail_mid = t @ Vector((px_val, 0.0, 0.0))
        for rz in (0.45, 0.95):
            create_beveled_box(bm, size=(0.08, depth, 0.12),
                               location=(rail_mid.x, rail_mid.y, rz),
                               rotation=(0.0, 0.0, rot_z),
                               mat_index=MAT_INDEX_TIMBER, bevel_amount=0.008)

    # Back fence line (Y = +half_d) - The Long Side
    for i in range(1, n_posts_x):
        px_val = -half_w + i * step_x
        p_world = t @ Vector((px_val, half_d, 0.0))
        create_beveled_box(bm, size=(0.16, 0.16, fence_h),
                           location=(p_world.x, p_world.y, fence_h * 0.5),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_TIMBER, bevel_amount=0.010)
    rail_back_mid = t @ Vector((0.0, half_d, 0.0))
    for rz in (0.45, 0.95):
        create_beveled_box(bm, size=(width, 0.08, 0.12),
                           location=(rail_back_mid.x, rail_back_mid.y, rz),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_TIMBER, bevel_amount=0.008)

    # Front fence line (Y = -half_d) with 3.4m center gate opening
    gap_half = 1.7
    fwd_out = t.to_3x3() @ Vector((0.0, -1.0, 0.0))
    for sgn in (-1.0, 1.0):
        # Gate post flanking the opening
        p_gate = t @ Vector((sgn * gap_half, -half_d, 0.0))
        post_gh = fence_h + 0.35
        create_beveled_box(bm, size=(0.20, 0.20, post_gh),
                           location=(p_gate.x, p_gate.y, post_gh * 0.5),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_TIMBER, bevel_amount=0.012)
        # Pyramid timber cap atop gate post
        create_cone(bm, radius1=0.15, radius2=0.0, height=0.14, segments=4,
                    location=(p_gate.x, p_gate.y, post_gh + 0.07),
                    rotation=(0.0, 0.0, rot_z + math.pi * 0.25), mat_index=MAT_INDEX_TIMBER)

        # Proud heraldic round shield on the outer front face with iron mounting plate
        sh_bracket = p_gate + fwd_out * 0.10 + Vector((0.0, 0.0, 0.85))
        create_beveled_box(bm, size=(0.16, 0.04, 0.16),
                           location=(sh_bracket.x, sh_bracket.y, sh_bracket.z),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_IRON, bevel_amount=0.005)
        sh_loc = p_gate + fwd_out * 0.13 + Vector((0.0, 0.0, 0.85))
        build_round_shield(bm, (sh_loc.x, sh_loc.y, sh_loc.z),
                           normal=fwd_out, radius=0.26, pattern='QUARTERED')

        # Wings from corner post to gate post
        wing_len = half_w - gap_half
        wing_mid = t @ Vector((sgn * (gap_half + wing_len * 0.5), -half_d, 0.0))
        for rz in (0.45, 0.95):
            create_beveled_box(bm, size=(wing_len, 0.08, 0.12),
                               location=(wing_mid.x, wing_mid.y, rz),
                               rotation=(0.0, 0.0, rot_z),
                               mat_index=MAT_INDEX_TIMBER, bevel_amount=0.008)

    # 2. Archery Target Range (on the long side - back fence, left half): exactly 2 butts
    target_y = half_d - 2.2
    target_xs = (-9.6, -5.0)
    for tx_val in target_xs:
        tp_world = t @ Vector((tx_val, target_y, 0.0))
        build_archery_target(bm, tp_world.x, tp_world.y, 0.0, ang=rot_z)

    # Dedicated timber shooting line rail for the 2 archery targets
    shoot_y = target_y - 9.5
    shoot_w = 7.8
    shoot_cx = (target_xs[0] + target_xs[1]) * 0.5
    shoot_line = t @ Vector((shoot_cx, shoot_y, 0.06))
    create_beveled_box(bm, size=(shoot_w, 0.16, 0.10),
                       location=(shoot_line.x, shoot_line.y, shoot_line.z),
                       rotation=(0.0, 0.0, rot_z),
                       mat_index=MAT_INDEX_TIMBER, bevel_amount=0.010)

    # Arrow barrels beside the archery shooting rail
    for sgn_b in (-1.0, 1.0):
        bar_pos = t @ Vector((shoot_cx + sgn_b * (shoot_w * 0.5 + 0.55), shoot_y, 0.0))
        build_barrel(bm, x=bar_pos.x, y=bar_pos.y, z_ground=0.0, radius=0.26, height=0.62)

    # 3. Sparring Arena (right half of the yard): dedicated 8.4m octagonal timber combat ring
    arena_cx = half_w * 0.44
    arena_cy = 1.0
    arena_r = 4.2
    n_ring_posts = 8
    ring_post_h = 1.08

    arena_local_pts = []
    for k in range(n_ring_posts):
        ang_k = k * (2.0 * math.pi / n_ring_posts) + (math.pi / n_ring_posts)
        arena_local_pts.append(Vector((arena_cx + arena_r * math.cos(ang_k),
                                       arena_cy + arena_r * math.sin(ang_k), 0.0)))

    # Find the ring segment facing southwest towards the gate/yard aisle to leave open as entrance
    open_seg_idx = 0
    best_dot = -999.0
    target_entrance_dir = Vector((-0.8, -0.6, 0.0)).normalized()
    for k in range(n_ring_posts):
        mid_pt = (arena_local_pts[k] + arena_local_pts[(k + 1) % n_ring_posts]) * 0.5
        dir_from_center = (mid_pt - Vector((arena_cx, arena_cy, 0.0))).normalized()
        dot_val = dir_from_center.dot(target_entrance_dir)
        if dot_val > best_dot:
            best_dot = dot_val
            open_seg_idx = k

    # Build the 8 perimeter posts of the sparring ring
    for p_loc in arena_local_pts:
        p_world = t @ p_loc
        create_beveled_box(bm, size=(0.16, 0.16, ring_post_h),
                           location=(p_world.x, p_world.y, ring_post_h * 0.5),
                           rotation=(0.0, 0.0, rot_z),
                           mat_index=MAT_INDEX_TIMBER, bevel_amount=0.010)
        # Pyramid timber cap
        create_cone(bm, radius1=0.12, radius2=0.0, height=0.10, segments=4,
                    location=(p_world.x, p_world.y, ring_post_h + 0.05),
                    rotation=(0.0, 0.0, rot_z + math.pi * 0.25), mat_index=MAT_INDEX_TIMBER)

    # Build rails and ground curb around the sparring arena ring
    for k in range(n_ring_posts):
        p1 = arena_local_pts[k]
        p2 = arena_local_pts[(k + 1) % n_ring_posts]
        mid_local = (p1 + p2) * 0.5
        seg_len = (p2 - p1).length
        seg_dir = (p2 - p1).normalized()
        seg_ang = math.atan2(seg_dir.y, seg_dir.x) + rot_z
        mid_w = t @ mid_local

        # Low ground plinth / border curb beam on all segments
        create_beveled_box(bm, size=(seg_len, 0.12, 0.10),
                           location=(mid_w.x, mid_w.y, 0.05),
                           rotation=(0.0, 0.0, seg_ang),
                           mat_index=MAT_INDEX_TIMBER, bevel_amount=0.008)

        # Upper and lower rails on all segments except the walk-in entrance opening
        if k != open_seg_idx:
            for rz in (0.46, 0.92):
                create_beveled_box(bm, size=(seg_len, 0.07, 0.10),
                                   location=(mid_w.x, mid_w.y, rz),
                                   rotation=(0.0, 0.0, seg_ang),
                                   mat_index=MAT_INDEX_TIMBER, bevel_amount=0.006)

    # Inside the Sparring Arena: central practice pell and combat training dummies
    pell_pos = t @ Vector((arena_cx, arena_cy, 0.0))
    create_cylinder(bm, radius=0.42, height=0.18, segments=12,
                    location=(pell_pos.x, pell_pos.y, 0.09), mat_index=MAT_INDEX_TIMBER)
    create_cylinder(bm, radius=0.18, height=1.90, segments=10,
                    location=(pell_pos.x, pell_pos.y, 0.95), mat_index=MAT_INDEX_TIMBER)
    create_cylinder(bm, radius=0.20, height=0.62, segments=10,
                    location=(pell_pos.x, pell_pos.y, 1.25), mat_index=MAT_INDEX_WOOD)

    # Two swivel combat dummies inside the arena flanking the pell
    dummy_pos1 = t @ Vector((arena_cx - 2.0, arena_cy + 1.2, 0.0))
    dummy_pos2 = t @ Vector((arena_cx + 2.0, arena_cy - 1.2, 0.0))
    build_training_dummy(bm, dummy_pos1.x, dummy_pos1.y, 0.0, ang=rot_z + 0.35)
    build_training_dummy(bm, dummy_pos2.x, dummy_pos2.y, 0.0, ang=rot_z - 0.35)

    # Outside the Sparring Arena: Weapon rack with armory crate beside the arena entrance
    rack_pos = t @ Vector((arena_cx - 4.4, arena_cy - 3.2, 0.0))
    build_weapon_rack(bm, rack_pos.x, rack_pos.y, 0.0, ang=rot_z + math.pi * 0.22)
    crate_wep = t @ Vector((arena_cx - 4.8, arena_cy - 2.3, 0.0))
    build_crate(bm, x=crate_wep.x, y=crate_wep.y, z_ground=0.0, size=0.52, height=0.46, ang=0.18)

    # Spectator / trainer benches overlooking the sparring arena
    # Bench 1: Along the right perimeter fence, turned facing left into the arena
    bench_right = t @ Vector((half_w - 1.4, arena_cy, 0.0))
    build_bench(bm, x=bench_right.x, y=bench_right.y, z_ground=0.0,
                ang=rot_z - math.pi * 0.5, length=2.2)

    # Bench 2: Behind the arena along back fence, facing forward into the arena
    bench_back = t @ Vector((arena_cx, half_d - 1.4, 0.0))
    build_bench(bm, x=bench_back.x, y=bench_back.y, z_ground=0.0,
                ang=rot_z + math.pi, length=2.2)

    # 4. Logistics, Armorer Supplies & Archery Spectator Seating
    # Archery spectator bench near the front fence
    bench_front = t @ Vector((shoot_cx, -half_d + 1.6, 0.0))
    build_bench(bm, x=bench_front.x, y=bench_front.y, z_ground=0.0,
                ang=rot_z + math.pi, length=2.0)

    # Armorer crates, tool chest, and water cooling trough on the front right
    crate_pos = t @ Vector((gap_half + 2.2, -half_d + 1.4, 0.0))
    build_crate(bm, x=crate_pos.x, y=crate_pos.y, z_ground=0.0, size=0.68, height=0.55)
    build_crate(bm, x=crate_pos.x + 0.72, y=crate_pos.y, z_ground=0.0, size=0.50, height=0.45, ang=0.25)
    build_barrel(bm, x=crate_pos.x + 1.45, y=crate_pos.y + 0.15, z_ground=0.0)
    # Water cooling trough for swords & cleaning
    trough_pos = t @ Vector((gap_half + 2.8, -half_d + 2.5, 0.20))
    create_beveled_box(bm, size=(1.20, 0.55, 0.40),
                       location=(trough_pos.x, trough_pos.y, trough_pos.z),
                       rotation=(0.0, 0.0, rot_z),
                       mat_index=MAT_INDEX_TIMBER, bevel_amount=0.02)

    # 5. Heraldic Banner Pole
    pole_pos = t @ Vector((-gap_half - 0.30, -half_d - 0.20, 0.0))
    build_banner_pole(bm, x=pole_pos.x, y=pole_pos.y, z_ground=0.0, height=5.4)


# -----------------------------------------------------------------------------
# Yard awnings (reused from the warehouse supply yard)
# -----------------------------------------------------------------------------

def _build_awning_at(bm, kind, cx, cy, z_base, rot_z=0.0, **kw):
    """Place a warehouse yard awning, rotated about its own footprint centre."""
    from .warehouse import build_tarp_awning, build_lean_to_awning
    before = set(bm.faces)
    if kind == 'TARP':
        build_tarp_awning(bm, cx=cx, cy=cy, z_base=z_base, **kw)
    else:
        build_lean_to_awning(bm, cx=cx, cy=cy, z_base=z_base, **kw)
    new_faces = [f for f in bm.faces if f not in before]
    if abs(rot_z) > 1e-6 and new_faces:
        piv = Matrix.Translation((cx, cy, 0.0))
        mat = piv @ Matrix.Rotation(rot_z, 4, 'Z') @ piv.inverted()
        transform_faces(new_faces, mat)


def _awning_on_front(bm, kind, ox, oy, rot, bld_depth, **kw):
    """Back a yard awning onto a building front (its tall back against the wall)."""
    nx, ny = math.sin(rot), -math.cos(rot)          # outward facade normal
    off = bld_depth * 0.5 + 0.55
    _build_awning_at(bm, kind, cx=ox + nx * off, cy=oy + ny * off,
                     z_base=0.0, rot_z=rot, **kw)


def _stock_shelter(bm, cx, cy, rng_sign):
    """Stack crates, barrels and glazed pots under a yard shelter like a private store."""
    build_crate(bm, x=cx - 0.68, y=cy - 0.42, z_ground=0.0, size=0.62, depth=0.50, height=0.54)
    build_crate(bm, x=cx - 0.62, y=cy - 0.40, z_ground=0.54, size=0.46, height=0.44)
    build_crate(bm, x=cx + 0.55, y=cy - 0.50, z_ground=0.0, size=0.50, height=0.52, ang=0.15)
    build_barrel(bm, x=cx + 0.62, y=cy + 0.35, z_ground=0.0, ang=0.4, radius=0.31, height=0.70)
    build_barrel(bm, x=cx + 0.10, y=cy + 0.55, z_ground=0.0, ang=1.1, radius=0.28, height=0.64)
    build_clay_pot(bm, x=cx - 0.32, y=cy + 0.52, z_ground=0.0, ang=0.4,
                   radius=0.20, height=0.50, pot_type='JAR')
    build_clay_pot(bm, x=cx + 0.04, y=cy + 0.30, z_ground=0.0, ang=-0.5,
                   radius=0.17, height=0.44, pot_type='URN')


def _awning_on_gable(bm, kind, ox, oy, rot, half_len, side_sign=1.0, **kw):
    """Back a yard shelter onto a building's gable end (local +/-X), like an
    attached lean-to tucked against the wall."""
    nx, ny = math.cos(rot) * side_sign, math.sin(rot) * side_sign
    depth = kw.get('depth', 2.4)
    off = half_len + depth * 0.5 + 0.05
    _build_awning_at(bm, kind, cx=ox + nx * off, cy=oy + ny * off, z_base=0.0,
                     rot_z=rot + side_sign * math.pi * 0.5, **kw)


def _place_estate_awnings(bm, props, tier, spread_x, fore_y, stable=None, servant=None):
    """Rustic yard shelters stocked as private little stores.

    Each is backed against an outbuilding's gable end when that outbuilding exists
    (so they read as attached lean-tos, not floating in the courtyard); otherwise
    they fall back to the open forecourt.
    """
    shelters = (
        ('TARP', stable, -spread_x * 0.55, 'LEANTO', 3.4, 2.8, 2.25, 2.80),
        # Servant lean-to rides high: the back beam clears the ground-floor
        # window heads and open shutters (~2.5m), and the extra width covers
        # the window bay instead of clipping through it.
        ('LEANTO', servant, spread_x * 0.55, 'TARP', 3.6, 2.4, 2.60, 3.20),
    )
    for kind, slot, fallback_x, _other, width, depth, fh, bh in shelters:
        if slot is not None:
            ox, oy, rot, olen = slot
            outward = 1.0 if (math.cos(rot) * ox + math.sin(rot) * oy) >= 0.0 else -1.0
            nx, ny = math.cos(rot) * outward, math.sin(rot) * outward
            off = olen * 0.5 + depth * 0.5 + 0.05
            cx, cy = ox + nx * off, oy + ny * off
            aw_rot = rot + outward * math.pi * 0.5
        else:
            cx, cy = fallback_x, fore_y + 4.8
            aw_rot = 0.0 if kind == 'TARP' else math.pi * 0.5
        _build_awning_at(bm, kind, cx=cx, cy=cy, z_base=0.0, rot_z=aw_rot,
                         width=width, depth=depth, front_h=fh, back_h=bh)
        _stock_shelter(bm, cx, cy, 1.0 if cx >= 0.0 else -1.0)


def build_estate_outbuildings(bm, props, ctx):
    """
    High-level orchestrator called during architectural accessories dispatch.
    Places the detached stables, servant quarters, guardhouse, forge, granary,
    courtyard fountain and awnings procedurally according to scene properties.
    """
    tier = getattr(props, 'material_tier', 'TIER_1')
    has_stable = getattr(props, 'has_stable', False)
    has_servants = getattr(props, 'has_servant_quarters', False)
    has_guardhouse = getattr(props, 'has_estate_guardhouse', False)
    has_forge = getattr(props, 'has_estate_forge', False)
    has_granary = getattr(props, 'has_estate_granary', False)
    has_chapel = getattr(props, 'has_estate_chapel', False)
    has_training = getattr(props, 'has_estate_training_grounds', False)
    has_fountain = getattr(props, 'has_estate_fountain', False)
    has_awnings = getattr(props, 'estate_awnings', False)

    if not (has_stable or has_servants or has_guardhouse or has_forge or has_granary or has_chapel or has_training or has_fountain or has_awnings):
        return

    spread_x = getattr(props, 'outbuilding_offset_x', 24.0)
    fore_y = getattr(props, 'outbuilding_offset_y', -10.0)
    stable_side = getattr(props, 'stable_side', 'LEFT')
    servant_side = getattr(props, 'servant_quarters_side', 'RIGHT')
    setback = getattr(props, 'plot_setback', 0.0)
    base_hy = ctx.base_d * 0.5

    # 1. Central Courtyard Fountain — centred in the honor court.
    if has_fountain:
        manor_front = setback - base_hy
        fountain_y = (fore_y + manor_front) * 0.5
        fountain_y = min(fountain_y, fore_y + 2.0)
        build_estate_fountain(bm, pos=(0.0, fountain_y, 0.0), tier=tier)

    stable_slot = None
    servant_slot = None

    # On grand estate compounds (such as the 200m x 200m Nasher's Manor plot where spread_x > 35m):
    # Outbuildings scale dramatically across tiers, culminating in a complete citadel mini-city in Tier 3!
    is_grand_plot = spread_x > 35.0

    if is_grand_plot and tier == 'TIER_3':
        # =========================================================================
        # TIER 3: CITADEL MINI-CITY (Walled Medieval Town Inside the Bailey)
        # Organic, creative layout: buildings hug the perimeter curtain walls in
        # distinct functional medieval quarters, clearing a massive Cour d'Honneur.
        # =========================================================================

        # --- 1. SOUTH-WEST: ARMORER'S & MILITARY TRAINING QUARTER ---
        # 1a. Ducal Armory & Foundry (Tucked deep into South-West wall corner)
        if has_forge:
            build_estate_forge(bm, props, pos=(-72.0, -70.0, 0.0), rot_z=math.radians(65.0),
                               tier=tier, width=16.0, depth=9.5, floors=2)

        # 1b. Military Training Grounds & Archery Yard (South perimeter wall)
        if has_training:
            build_estate_training_grounds(bm, pos=(-40.0, -68.0, 0.0), rot_z=math.radians(6.0),
                                          tier=tier, width=26.0, depth=18.0)

        # --- 2. WEST: EQUESTRIAN & RETAINERS QUARTER ---
        # 2a. Master Equestrian Stables (Backed directly against West curtain wall)
        if has_stable:
            build_stable(bm, props, pos=(-74.0, -25.0, 0.0), rot_z=math.radians(88.0),
                         tier=tier, width=22.0, depth=10.0)
            stable_slot = (-74.0, -25.0, math.radians(88.0), 22.0)

        # 2b. Chamberlain's Residence (Backed along West curtain wall)
        build_retainer_house(bm, props, pos=(-73.0, 18.0, 0.0), rot_z=math.radians(92.0),
                             tier=tier, width=15.0, depth=9.0, floors=2, name="Chamberlain")

        # --- 3. NORTH-WEST: GARRISON & GRANARY CORNER ---
        # 3a. Garrison Barracks Tenement (Angled diagonally into North-West corner bastion)
        build_tenement_building(bm, props, pos=(-65.0, 56.0, 0.0), rot_z=math.radians(48.0),
                                tier=tier, width=24.0, depth=11.0, floors=3)

        # 3b. Provisions Granary (Tucked along North curtain wall)
        if has_granary:
            build_estate_granary(bm, props, pos=(-35.0, 72.0, 0.0), rot_z=math.radians(8.0),
                                 tier=tier, width=16.0, depth=9.0, floors=2)

        # --- 4. SOUTH-EAST: GATE WATCH & SANCTUARY NOOK ---
        # 4a. Gatehouse Watch Barracks (Tucked into South-East wall corner)
        if has_guardhouse:
            build_guardhouse(bm, props, pos=(72.0, -70.0, 0.0), rot_z=math.radians(-65.0),
                             tier=tier, width=16.0, depth=8.5, floors=2)

        # 4b. Consecrated Chantry Chapel (Sanctuary nook along South wall)
        if has_chapel:
            build_estate_chapel(bm, props, pos=(40.0, -68.0, 0.0), rot_z=math.radians(-6.0),
                                tier=tier, width=15.0, depth=9.0, floors=1)

        # --- 5. EAST: NOBLE RETAINERS QUARTER ---
        # 5a. Castellan's Grand Manor House (Backed directly against East curtain wall)
        if has_servants:
            build_retainer_house(bm, props, pos=(74.0, -25.0, 0.0), rot_z=math.radians(-88.0),
                                 tier=tier, width=18.0, depth=10.0, floors=2, name="Castellan")
            servant_slot = (74.0, -25.0, math.radians(-88.0), 18.0)

        # 5b. High Steward's Chancellor Manor (Backed along East curtain wall)
        build_retainer_house(bm, props, pos=(73.0, 18.0, 0.0), rot_z=math.radians(-92.0),
                             tier=tier, width=15.0, depth=9.0, floors=2, name="HighSteward")

        # --- 6. NORTH-EAST: CRAFTSMEN & SCHOLAR CORNER ---
        # 6a. Servants' & Craftsmen Tenement (Angled diagonally into North-East corner bastion)
        build_tenement_building(bm, props, pos=(65.0, 56.0, 0.0), rot_z=math.radians(-48.0),
                                tier=tier, width=24.0, depth=11.0, floors=3)

        # 6b. Almoner & Scholar Retainer Residence (Tucked along North curtain wall)
        build_retainer_house(bm, props, pos=(35.0, 72.0, 0.0), rot_z=math.radians(-8.0),
                             tier=tier, width=15.0, depth=9.0, floors=2, name="Almoner")

        # --- 7. COURTYARD AWNINGS & SUPPLY STORES ---
        if has_awnings:
            _place_estate_awnings(bm, props, tier, spread_x, fore_y,
                                  stable=stable_slot, servant=servant_slot)
        return



    if is_grand_plot and tier == 'TIER_2':
        # =========================================================================
        # TIER 2: SEIGNORIAL CHATELET (6 Outbuildings Growing with Tier)
        # =========================================================================
        # Master Stables (20m x 10m)
        if has_stable:
            build_stable(bm, props, pos=(-56.0, -16.0, 0.0), rot_z=math.pi * 0.5,
                         tier=tier, width=20.0, depth=10.0)
            stable_slot = (-56.0, -16.0, math.pi * 0.5, 20.0)

        # Retainers' Hall (16m x 8.5m, 2 floors)
        if has_servants:
            build_retainer_house(bm, props, pos=(56.0, -16.0, 0.0), rot_z=-math.pi * 0.5,
                                 tier=tier, width=16.0, depth=8.5, floors=2, name="Retainers")
            servant_slot = (56.0, -16.0, -math.pi * 0.5, 16.0)

        # Servants' Quarters (16m x 8m, 2 floors)
        build_servant_quarters(bm, props, pos=(56.0, 14.0, 0.0), rot_z=-math.pi * 0.5,
                               tier=tier, width=16.0, depth=8.0, floors=2)

        # Gate Guardhouse (13.5m x 7m, 2 floors)
        if has_guardhouse:
            build_guardhouse(bm, props, pos=(56.0, -46.0, 0.0), rot_z=-math.pi * 0.5,
                             tier=tier, width=13.5, depth=7.0, floors=2)

        # Armory Forge (13m x 7.5m)
        if has_forge:
            build_estate_forge(bm, props, pos=(-56.0, -46.0, 0.0), rot_z=math.pi * 0.5,
                               tier=tier, width=13.0, depth=7.5, floors=1)

        # Granary (12m x 7m)
        if has_granary:
            build_estate_granary(bm, props, pos=(-56.0, 14.0, 0.0), rot_z=math.pi * 0.5,
                                 tier=tier, width=12.0, depth=7.0, floors=1)

        # Training Grounds (28m x 20m)
        if has_training:
            build_estate_training_grounds(bm, pos=(-32.0, -50.0, 0.0), rot_z=0.0,
                                          tier=tier, width=28.0, depth=20.0)

        if has_awnings:
            _place_estate_awnings(bm, props, tier, spread_x, fore_y,
                                  stable=stable_slot, servant=servant_slot)
        return

    # Standard Plot / Tier 1 Layout
    # 2. Horse Stable & Carriage Barn
    if has_stable:
        st_sgn = -1.0 if stable_side == 'LEFT' else 1.0
        st_x = st_sgn * spread_x
        st_y = fore_y
        _rot_on = getattr(props, 'stable_rotate', False) or spread_x > 18.0
        st_rot = -math.pi * 0.5 * st_sgn if _rot_on else 0.0
        st_w = 16.0 if is_grand_plot else None
        st_d = 9.0 if is_grand_plot else None
        build_stable(bm, props, pos=(st_x, st_y, 0.0), rot_z=st_rot, tier=tier,
                     width=st_w, depth=st_d)
        stable_slot = (st_x, st_y, st_rot, st_w if st_w else _stable_dims(tier)[0])

    # 3. Servant Quarters / Steward Lodge
    if has_servants:
        sq_sgn = -1.0 if servant_side == 'LEFT' else 1.0
        sq_x = sq_sgn * spread_x
        sq_y = fore_y
        sq_rot = -math.pi * 0.5 * sq_sgn if spread_x > 18.0 else 0.0
        sq_w = 14.0 if is_grand_plot else (13.5 if tier == 'TIER_3' else (12.0 if tier == 'TIER_2' else 10.5))
        sq_d = 7.5 if tier == 'TIER_3' else 6.8
        sq_fl = 2 if (tier in ('TIER_2', 'TIER_3') or is_grand_plot) else 1
        build_servant_quarters(
            bm, props, pos=(sq_x, sq_y, 0.0), rot_z=sq_rot, tier=tier,
            width=sq_w, depth=sq_d, floors=sq_fl
        )
        servant_slot = (sq_x, sq_y, sq_rot, sq_w)

    # 4. Gate Guardhouse & Watch Lodge
    if has_guardhouse:
        gh_sgn = 1.0 if servant_side == 'RIGHT' else -1.0
        gh_x = gh_sgn * (spread_x * 0.98 if spread_x > 26.0 else spread_x * 0.90)
        gh_y = fore_y - 18.0
        gh_rot = -math.pi * 0.5 * gh_sgn
        gh_fl = 2 if tier == 'TIER_3' else 1
        build_guardhouse(
            bm, props, pos=(gh_x, gh_y, 0.0), rot_z=gh_rot, tier=tier,
            width=11.5 if is_grand_plot else 10.0, depth=6.5, floors=gh_fl
        )

    # 5. Estate Armory & Forge
    if has_forge:
        fg_sgn = -1.0 if stable_side == 'LEFT' else 1.0
        fg_x = fg_sgn * (spread_x * 0.98 if spread_x > 26.0 else spread_x * 0.90)
        fg_y = fore_y - 18.0
        fg_rot = -math.pi * 0.5 * fg_sgn
        fg_fl = 1
        build_estate_forge(
            bm, props, pos=(fg_x, fg_y, 0.0), rot_z=fg_rot, tier=tier,
            width=11.0 if is_grand_plot else 10.0, depth=6.5, floors=fg_fl
        )

    # 6. Estate Granary & Provisions Storehouse
    if has_granary:
        gn_sgn = -1.0 if stable_side == 'LEFT' else 1.0
        gn_x = gn_sgn * (spread_x + 1.8 if spread_x > 26.0 else spread_x * 1.05)
        gn_y = fore_y + 16.0
        gn_rot = -math.pi * 0.5 * gn_sgn
        build_estate_granary(
            bm, props, pos=(gn_x, gn_y, 0.0), rot_z=gn_rot, tier=tier,
            width=9.5, depth=6.0, floors=1
        )

    # 7. Estate Chantry Chapel & Treasury
    if has_chapel:
        ch_sgn = 1.0 if servant_side == 'RIGHT' else -1.0
        ch_x = ch_sgn * (spread_x + 1.8 if spread_x > 26.0 else spread_x * 1.05)
        ch_y = fore_y + 16.0
        ch_rot = -math.pi * 0.5 * ch_sgn
        build_estate_chapel(
            bm, props, pos=(ch_x, ch_y, 0.0), rot_z=ch_rot, tier=tier,
            width=11.0 if tier == 'TIER_3' else 9.5, depth=6.5, floors=1
        )

    # 8. Estate Training Grounds & Archery Yard
    if has_training:
        tr_sgn = -1.0 if stable_side == 'LEFT' else 1.0
        tr_w = 32.0 if tier == 'TIER_3' else 26.0
        tr_d = 22.0 if tier == 'TIER_3' else 18.0
        tr_x = tr_sgn * (spread_x * 0.46)
        tr_y = fore_y - 24.0
        build_estate_training_grounds(bm, pos=(tr_x, tr_y, 0.0), rot_z=0.0, tier=tier,
                                      width=tr_w, depth=tr_d)

    # 9. Yard shelters backed onto the outbuilding gables
    if has_awnings:
        _place_estate_awnings(bm, props, tier, spread_x, fore_y,
                              stable=stable_slot, servant=servant_slot)
