"""
Estate Grounds & Outbuildings Generator for BlendBuildingCreator.

Procedurally constructs detached outbuildings (stables, carriage barn, servant quarters /
steward lodge) and central courtyard focal points (ornate stone fountain, yard awnings)
for grand noble compounds and estates.

The detached outbuildings are not hand-modelled from raw boxes; they are generated by the
real main building pipeline (walls, floors, openings, roof) into a temporary mesh and then
transformed and merged into the estate mesh, so they read as genuine miniature buildings.
"""

import math
from mathutils import Vector, Matrix, Euler

from ..mesh_utils import (
    create_box, create_beveled_box, create_cylinder, create_cone, transform_faces
)
from ..materials import (
    MAT_INDEX_STONE, MAT_INDEX_CUT_STONE, MAT_INDEX_TIMBER,
    MAT_INDEX_TIMBER_FRAME, MAT_INDEX_WOOD, MAT_INDEX_SHINGLES,
    MAT_INDEX_PLASTER_EXT, MAT_INDEX_IRON, MAT_INDEX_GLASS,
    MAT_INDEX_FLOOR, MAT_INDEX_TARP
)
from .furniture import build_barrel, build_crate, build_clay_pot


def _fx_ring_shell(bm, cx, cy, z0, z1, r_out0, r_out1, r_in0, r_in1, segments, mat,
                   close_bottom=True):
    """Smooth hollow conical ring (frustum shell): outer + inner walls, annulus caps.

    Used for the fountain's pool rim and upper bowl so the water can sit *inside*
    the stone with clearance instead of being a coplanar disc buried in a solid
    cylinder. ``segments`` should be high (40-48) to keep the silhouette round.
    """
    uv_layer = bm.loops.layers.uv.verify()
    outer0, outer1, inner0, inner1 = [], [], [], []
    for i in range(segments):
        a = 2.0 * math.pi * i / segments
        ca, sa = math.cos(a), math.sin(a)
        outer0.append(bm.verts.new((cx + r_out0 * ca, cy + r_out0 * sa, z0)))
        outer1.append(bm.verts.new((cx + r_out1 * ca, cy + r_out1 * sa, z1)))
        inner0.append(bm.verts.new((cx + r_in0 * ca, cy + r_in0 * sa, z0)))
        inner1.append(bm.verts.new((cx + r_in1 * ca, cy + r_in1 * sa, z1)))
    circ_out = 2.0 * math.pi * max(r_out0, 1e-4)
    circ_in = 2.0 * math.pi * max(r_in0, 1e-4)
    h = z1 - z0
    faces = []
    for i in range(segments):
        n = (i + 1) % segments
        # Outer wall (normal points radially outward).
        f = bm.faces.new([outer0[i], outer0[n], outer1[n], outer1[i]])
        f.material_index = mat
        u0 = circ_out * i / segments
        u1 = circ_out * (i + 1) / segments
        f.loops[0][uv_layer].uv = Vector((u0, 0.0))
        f.loops[1][uv_layer].uv = Vector((u1, 0.0))
        f.loops[2][uv_layer].uv = Vector((u1, h))
        f.loops[3][uv_layer].uv = Vector((u0, h))
        faces.append(f)
        # Inner wall (normal points inward, into the pool/bowl).
        f = bm.faces.new([inner0[n], inner0[i], inner1[i], inner1[n]])
        f.material_index = mat
        u0 = circ_in * i / segments
        u1 = circ_in * (i + 1) / segments
        f.loops[0][uv_layer].uv = Vector((u0, 0.0))
        f.loops[1][uv_layer].uv = Vector((u1, 0.0))
        f.loops[2][uv_layer].uv = Vector((u1, h))
        f.loops[3][uv_layer].uv = Vector((u0, h))
        faces.append(f)
        # Top annulus (planar projection, faces up).
        f = bm.faces.new([outer1[i], outer1[n], inner1[n], inner1[i]])
        f.material_index = mat
        for lp in f.loops:
            lp[uv_layer].uv = Vector((lp.vert.co.x, lp.vert.co.y))
        faces.append(f)
        # Bottom annulus (faces down).
        if close_bottom:
            f = bm.faces.new([outer0[i], inner0[i], inner0[n], outer0[n]])
            f.material_index = mat
            for lp in f.loops:
                lp[uv_layer].uv = Vector((lp.vert.co.x, lp.vert.co.y))
            faces.append(f)
    return faces


def build_estate_fountain(bm, pos=(0.0, -8.0, 0.0), tier='TIER_3'):
    """Smooth, round multi-tiered stone fountain for the central Cour d'Honneur.

    High-segment discs and true hollow rings keep the silhouette round; the pool and
    the upper catch-bowl are recessed so the water surface sits well below each rim
    with real clearance (no coplanar z-fighting between water and stone).
    """
    fx, fy, fz = pos
    big = tier == 'TIER_3'
    base_r = 3.6 if big else 2.8

    # 1. Stepped circular plinth (lower disc embeds slightly to avoid coincident planes).
    create_cylinder(bm, radius=base_r, height=0.22, segments=48,
                    location=(fx, fy, fz + 0.11), mat_index=MAT_INDEX_STONE)
    create_cylinder(bm, radius=base_r - 0.30, height=0.18, segments=48,
                    location=(fx, fy, fz + 0.30), mat_index=MAT_INDEX_CUT_STONE)
    z_plinth = fz + 0.39

    # 2. Pool: hollow ring rim with a flared coping, on a floor disc that stays just
    #    inside the rim (a hair of clearance so nothing is coplanar).
    basin_r = base_r - 0.45
    wall_t = 0.30
    pool_in = basin_r - wall_t
    create_cylinder(bm, radius=pool_in - 0.02, height=0.32, segments=48,
                    location=(fx, fy, z_plinth + 0.16), mat_index=MAT_INDEX_STONE)
    _fx_ring_shell(bm, fx, fy, z_plinth + 0.02, z_plinth + 0.66,
                   basin_r, basin_r + 0.07, pool_in, pool_in,
                   48, MAT_INDEX_CUT_STONE, close_bottom=True)
    # Recessed water surface, well below the coping (~0.3 m of freeboard).
    create_cylinder(bm, radius=pool_in - 0.04, height=0.015, segments=48,
                    location=(fx, fy, z_plinth + 0.36), mat_index=MAT_INDEX_GLASS)
    z_floor_top = z_plinth + 0.32

    # 3. Central pedestal rising out of the pool.
    ped_r = 0.52 if big else 0.40
    ped_h = 1.45
    create_cylinder(bm, radius=ped_r + 0.16, height=0.26, segments=36,
                    location=(fx, fy, z_floor_top + 0.11), mat_index=MAT_INDEX_STONE)
    create_cylinder(bm, radius=ped_r, height=ped_h, segments=36,
                    location=(fx, fy, z_floor_top + 0.24 + ped_h * 0.5),
                    mat_index=MAT_INDEX_CUT_STONE)

    # 4. Upper catch-bowl: flared hollow ring with its own recessed water.
    bowl_z0 = z_floor_top + 0.24 + ped_h
    bowl_r = 1.15 if big else 0.90
    bowl_h = 0.50
    bowl_z1 = bowl_z0 + bowl_h
    _fx_ring_shell(bm, fx, fy, bowl_z0, bowl_z1,
                   ped_r + 0.02, bowl_r, ped_r - 0.10, bowl_r - 0.14,
                   40, MAT_INDEX_CUT_STONE, close_bottom=False)
    create_cylinder(bm, radius=bowl_r - 0.16, height=0.015, segments=40,
                    location=(fx, fy, bowl_z1 - 0.11), mat_index=MAT_INDEX_GLASS)

    # 5. Central jet spire.
    create_cylinder(bm, radius=0.14, height=bowl_h + 0.30, segments=20,
                    location=(fx, fy, bowl_z0 + (bowl_h + 0.30) * 0.5),
                    mat_index=MAT_INDEX_CUT_STONE)
    finial_h = 0.80
    create_cone(bm, radius1=0.20, radius2=0.04, height=finial_h, segments=20,
                location=(fx, fy, bowl_z1 + 0.12 + finial_h * 0.5),
                mat_index=MAT_INDEX_CUT_STONE)
    create_cylinder(bm, radius=0.09, height=0.16, segments=12,
                    location=(fx, fy, bowl_z1 + 0.12 + finial_h + 0.06),
                    mat_index=MAT_INDEX_IRON)



# -----------------------------------------------------------------------------
# Reusable detached-building generation (reuses the main building pipeline)
# -----------------------------------------------------------------------------

# Estate/fotification toggles that must never be inherited by a generated outbuilding,
# otherwise every stable would recursively spawn its own stables and walls.
_OUTHOUSE_DISABLED = (
    'has_stable', 'has_servant_quarters', 'has_estate_fountain',
    'has_palisade', 'has_curtain_wall', 'has_banners',
    'has_bastion_towers', 'has_military_props', 'has_mounted_shields',
    'has_gable_crest', 'has_side_annex', 'has_mini_wing',
    'has_balcony', 'has_corner_turrets', 'has_clock_tower',
    'has_veranda', 'has_trade_sign', 'has_flower_boxes',
    'has_outdoor_decor', 'has_well', 'has_arched_porch',
    'has_side_rampart', 'has_pillared_overhang',
)

_INHERITED = (
    'color_shingles', 'color_wall_ext', 'color_timber', 'color_stone',
    'color_floor', 'color_timber_frame', 'window_glow_strength',
    'include_door_leaves',
)


def _merge_generated_building(bm, base_props, overrides, pos=0.0, rot_z=0.0, preset_key=None):
    """Generate a detached building with the real pipeline and merge it into ``bm``.

    Builds a genuine miniature building using :func:`generate_building` (same walls,
    floors, openings, roof and materials as the main manor), bakes the placement
    transform into a temporary mesh, then appends it to the shared bmesh. Material
    slot indices line up because both meshes use the same canonical slot order.

    When ``preset_key`` names a real style preset the outhouse is generated from that
    preset (e.g. the dedicated STABLE barn presets), with ``overrides`` then tuning the
    footprint and the placement.
    """
    import bpy
    from ..building import generate_building

    scene = bpy.data.scenes.new("_bbc_outhouse")
    mesh = bpy.data.meshes.new("_bbc_outhouse_mesh")
    obj = bpy.data.objects.new("_bbc_outhouse", mesh)
    try:
        op = scene.fantasy_building_settings
        op.auto_update = False
        op.building_archetype = 'NONE'
        if preset_key:
            try:
                from ...presets import PRESETS, apply_preset
                if preset_key in PRESETS:
                    apply_preset(op, preset_key)
                    op.auto_update = False
                    op.building_archetype = 'NONE'
            except Exception:
                pass
        op.material_tier = getattr(base_props, 'material_tier', 'TIER_1')
        for _ck in _INHERITED:
            if hasattr(base_props, _ck) and hasattr(op, _ck):
                try:
                    setattr(op, _ck, getattr(base_props, _ck))
                except Exception:
                    pass
        for _fk in _OUTHOUSE_DISABLED:
            if hasattr(op, _fk):
                try:
                    setattr(op, _fk, False)
                except Exception:
                    pass
        for k, v in overrides.items():
            if hasattr(op, k):
                try:
                    setattr(op, k, v)
                except Exception:
                    pass

        generate_building(obj, op)

        mat = (Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z'))
        mesh.transform(mat)
        bm.from_mesh(mesh)
    finally:
        bpy.data.objects.remove(obj, do_unlink=True)
        bpy.data.meshes.remove(mesh)
        bpy.data.scenes.remove(scene)


def _stable_key(tier):
    """Map a material tier ('TIER_1') to its STABLE preset key ('STABLE_T1')."""
    suffix = tier[-1] if tier else '1'
    return 'STABLE_T%s' % suffix


def _stable_dims(tier):
    """Footprint of the STABLE_<tier> preset, shared by the barn and the yard."""
    try:
        from ...presets import PRESETS
        s = PRESETS.get(_stable_key(tier), {}).get('settings', {})
        return s.get('width', 12.0), s.get('depth', 8.0)
    except Exception:
        return 12.0, 8.0


def build_stable(bm, props, pos=(-24.0, -10.0, 0.0), rot_z=0.0, tier='TIER_1'):
    """Detached horse stable & carriage barn.

    The ``STABLE_<tier>`` preset is the single source of truth for the barn (walls,
    timber door, roof — no foundation, no steps, no dormers), so a standalone stable
    built from that preset matches this estate outbuilding exactly. The working yard
    (stall row + paddock pen) is added by the same shared yard builder.
    """
    _merge_generated_building(bm, props, {}, pos=pos, rot_z=rot_z,
                              preset_key=_stable_key(tier))
    bw, bd = _stable_dims(tier)
    t = Matrix.Translation(Vector(pos)) @ Matrix.Rotation(rot_z, 4, 'Z')
    _build_stable_yard(bm, t, bw, bd, tier)


def build_stable_yard_for_building(bm, props, ctx):
    """Build the stall row + paddock pen when the main building itself is a stable.

    Called from the archetype dispatch so a standalone STABLE preset gets the same
    yard as the estate stable, keeping the two paths identical.
    """
    tier = getattr(props, 'material_tier', 'TIER_1')
    bw, bd = _stable_dims(tier)
    _build_stable_yard(bm, Matrix.Identity(4), bw, bd, tier)


def _local_box(bm, t, size, loc, mat=MAT_INDEX_TIMBER, bevel=0.01, rot=(0.0, 0.0, 0.0)):
    """Place a beveled box in an outbuilding's rotated local frame."""
    return create_beveled_box(
        bm, size=size, location=loc, rotation=rot,
        transform_matrix=t, mat_index=mat, bevel_amount=bevel,
    )


def _build_stall_shelter(bm, t, x0, x1, y_back, depth, tier='TIER_1', stalls=3,
                         back_h=2.15, front_h=2.15):
    """Open-front timber stall row with a framed lean-to roof, opening toward -Y.

    Tier 1 gets a simple cloth/plank skin over a visible rafter frame (lumbermill
    feel); higher tiers get shingles. The shelter is a flat-roofed run-in shed, so
    the back wall, stall dividers and both end walls all share one height (nothing
    steps or pokes through); only the open front is framed by posts.
    """
    w = x1 - x0
    cx = (x0 + x1) * 0.5
    y_front = y_back - depth
    slope = back_h - front_h
    ang = math.atan2(slope, depth)
    rl = math.hypot(depth, slope)
    mid_y = y_back - depth * 0.5
    roof_mid_z = (back_h + front_h) * 0.5
    # One shared wall height for the back wall, dividers and ends: it clears the
    # roof underside everywhere the roof is lowest.
    wall_h = min(back_h, front_h) - 0.05

    # Plank back wall.
    plank_h = 0.24
    for i in range(int(wall_h / plank_h)):
        _local_box(bm, t, (w, 0.10, min(plank_h * 0.94, wall_h - i * plank_h)),
                   (cx, y_back, plank_h * (i + 0.5)), mat=MAT_INDEX_WOOD, bevel=0.008)
    # Front posts.
    for i in range(stalls + 1):
        px = x0 + w * i / stalls
        _local_box(bm, t, (0.16, 0.16, front_h), (px, y_front, front_h * 0.5),
                   mat=MAT_INDEX_TIMBER, bevel=0.012)
    # Solid divider walls between stalls, at the same height as the back wall.
    for i in range(1, stalls):
        px = x0 + w * i / stalls
        _local_box(bm, t, (0.10, depth, wall_h),
                   (px, y_back - depth * 0.5, wall_h * 0.5), mat=MAT_INDEX_WOOD, bevel=0.008)
    # Solid end walls close both flanks, matching the back wall height.
    for sx in (x0, x1):
        _local_box(bm, t, (0.10, depth, wall_h), (sx, y_back - depth * 0.5, wall_h * 0.5),
                   mat=MAT_INDEX_WOOD, bevel=0.008)

    # Rafter frame: front header on the posts and a back plate sitting on the wall.
    _local_box(bm, t, (w + 0.20, 0.14, 0.16), (cx, y_front, front_h + 0.02),
               mat=MAT_INDEX_TIMBER, bevel=0.008)
    _local_box(bm, t, (w + 0.20, 0.14, 0.16), (cx, y_back, wall_h + 0.08),
               mat=MAT_INDEX_TIMBER, bevel=0.008)
    for i in range(stalls + 1):
        rx = x0 + w * i / stalls
        _local_box(bm, t, (0.09, rl + 0.10, 0.09), (rx, mid_y, roof_mid_z + 0.10),
                   rot=(ang, 0.0, 0.0), mat=MAT_INDEX_TIMBER, bevel=0.006)

    # Roof slab, framed by bargeboards (sides) and a fascia board (front eave).
    roof_mat = MAT_INDEX_TARP if tier == 'TIER_1' else MAT_INDEX_SHINGLES
    roof_faces = _local_box(
        bm, t, (w + 0.34, rl + 0.30, 0.055),
        (cx, mid_y, roof_mid_z + 0.17), rot=(ang, 0.0, 0.0),
        mat=roof_mat, bevel=0.006)
    half_rl = rl * 0.5 + 0.15
    front_y = mid_y - half_rl * math.cos(ang)
    front_z = roof_mid_z + 0.17 - half_rl * math.sin(ang)
    _local_box(bm, t, (w + 0.40, 0.11, 0.16), (cx, front_y, front_z),
               rot=(ang, 0.0, 0.0), mat=MAT_INDEX_TIMBER, bevel=0.008)
    for s in (-1.0, 1.0):
        _local_box(bm, t, (0.12, rl + 0.30, 0.16),
                   (cx + s * (w * 0.5 + 0.17), mid_y, roof_mid_z + 0.16),
                   rot=(ang, 0.0, 0.0), mat=MAT_INDEX_TIMBER, bevel=0.008)

    # Match the main-roof shingle UVs (correct axis + 0.32 tiles/m) instead of the
    # default box mapping that leaves the tiles rotated and mis-scaled.
    if roof_mat == MAT_INDEX_SHINGLES:
        from ..roof.shingles import map_lean_to_shingle_uvs
        loc_world = t @ Vector((cx, mid_y, roof_mid_z + 0.17))
        rot_world = (t.to_3x3() @ Euler((ang, 0.0, 0.0), 'XYZ').to_matrix()).to_euler()
        map_lean_to_shingle_uvs(bm, roof_faces, loc_world, rot_world,
                                u_scale=0.32, v_scale=0.32)


def _build_pen_fence(bm, t, x0, x1, y0, y1, gate_w=1.7, post_h=1.25):
    """A rail-and-post paddock fence around the pen, with a gate gap on the -Y side."""
    def run(ax, ay, bx, by):
        length = math.hypot(bx - ax, by - ay)
        n = max(1, int(round(length / 1.6)))
        ang = math.atan2(by - ay, bx - ax)
        for i in range(n + 1):
            fx = ax + (bx - ax) * i / n
            fy = ay + (by - ay) * i / n
            _local_box(bm, t, (0.14, 0.14, post_h), (fx, fy, post_h * 0.5),
                       mat=MAT_INDEX_TIMBER, bevel=0.010)
        for rz in (0.50, 1.00):
            _local_box(bm, t, (length + 0.08, 0.08, 0.10),
                       ((ax + bx) * 0.5, (ay + by) * 0.5, rz),
                       rot=(0.0, 0.0, ang), mat=MAT_INDEX_TIMBER, bevel=0.006)

    run(x0, y0, x0, y1)                 # left flank
    run(x1, y0, x1, y1)                 # right flank
    # NOTE: no rail across the barn facade — it would block the carriage door.
    # Courtyard side split by a gate opening aligned with the barn door.
    gate_lo = -gate_w * 0.5
    gate_hi = gate_w * 0.5
    run(x0, y1, gate_lo, y1)
    run(gate_hi, y1, x1, y1)
    for gx in (gate_lo, gate_hi):
        _local_box(bm, t, (0.18, 0.18, post_h + 0.35), (gx, y1, (post_h + 0.35) * 0.5),
                   mat=MAT_INDEX_TIMBER, bevel=0.014)


def _build_stable_yard(bm, t, barn_w, barn_d, tier):
    """Compose the stable yard: fenced paddock plus a roofed open stall row.

    The pen is open along the barn facade (no rail in front of the carriage door)
    so horses and carts can be walked straight in through the gate.
    """
    barn_front = -barn_d * 0.5
    pen_d = 6.0
    pen_w = barn_w + 1.0
    x0, x1 = -pen_w * 0.5, pen_w * 0.5
    y0 = barn_front - 0.30            # barn side of the pen
    y1 = barn_front - pen_d           # courtyard side

    # Open stall row tucked along the left side of the pen, opening to the court.
    stall_w = min(pen_w * 0.5, 4.2)
    _build_stall_shelter(bm, t, x0 + 0.15, x0 + 0.15 + stall_w, y0 - 0.20, 3.0,
                         tier=tier, stalls=3)
    _build_pen_fence(bm, t, x0, x1, y0, y1)


def build_servant_quarters(bm, props, pos=(24.0, -10.0, 0.0), rot_z=0.0, tier='TIER_1',
                           width=12.0, depth=7.0, floors=2, floor_h=2.7):
    """Detached servant lodge / steward residence, generated with the main building pipeline."""
    overrides = {
        'building_shape': 'RECTANGLE',
        'num_floors': max(1, floors),
        'floor_height': floor_h,
        'width': width,
        'depth': depth,
        'wall_thickness': 0.28,
        'has_cantilever': floors > 1,
        'overhang_mode': 'SECOND_FLOOR_ONLY',
        'cantilever_overhang': 0.22,
        'wonkiness': 0.0,
        'has_foundation': True,
        'foundation_height': 0.50,
        'ground_floor_stone': True,
        'has_ceiling_beams': False,
        'has_stairs': floors > 1,
        'stair_style': 'STRAIGHT',
        'has_front_door': True,
        'door_width': 1.35,
        'door_height': 2.25,
        'door_shape': 'AUTO',
        'door_angle': 0.0,
        'has_windows': True,
        'window_spacing': 2.4,
        'has_shutters': True,
        'shutter_state': 'OPEN',
        'has_timber_framing': True,
        'timber_diagonals': True,
        'roof_style': 'SWAY',
        'roof_orientation': 'FRONT_BACK',
        'roof_height': 2.6,
        'roof_overhang': 0.60,
        'has_roof_shingles': True,
        'has_dormers': False,
        'has_chimney': True,
        'chimney_pos_x': 0.55,
        'chimney_pos_y': 0.0,
    }
    _merge_generated_building(bm, props, overrides, pos=pos, rot_z=rot_z)


# -----------------------------------------------------------------------------
# Yard awnings (reused from the warehouse supply yard)
# -----------------------------------------------------------------------------

def _build_awning_at(bm, kind, cx, cy, z_base, rot_z=0.0, **kw):
    """Place a warehouse yard awning, rotated about its own footprint centre."""
    from .warehouse import build_tarp_awning, build_lean_to_awning
    before = set(bm.faces)
    if kind == 'TARP':
        build_tarp_awning(bm, cx=cx, cy=cy, z_base=z_base, **kw)
    else:
        build_lean_to_awning(bm, cx=cx, cy=cy, z_base=z_base, **kw)
    new_faces = [f for f in bm.faces if f not in before]
    if abs(rot_z) > 1e-6 and new_faces:
        piv = Matrix.Translation((cx, cy, 0.0))
        mat = piv @ Matrix.Rotation(rot_z, 4, 'Z') @ piv.inverted()
        transform_faces(new_faces, mat)


def _awning_on_front(bm, kind, ox, oy, rot, bld_depth, **kw):
    """Back a yard awning onto a building front (its tall back against the wall)."""
    nx, ny = math.sin(rot), -math.cos(rot)          # outward facade normal
    off = bld_depth * 0.5 + 0.55
    _build_awning_at(bm, kind, cx=ox + nx * off, cy=oy + ny * off,
                     z_base=0.0, rot_z=rot, **kw)


def _stock_shelter(bm, cx, cy, rng_sign):
    """Stack crates, barrels and glazed pots under a yard shelter like a private store."""
    build_crate(bm, x=cx - 0.68, y=cy - 0.42, z_ground=0.0, size=0.62, depth=0.50, height=0.54)
    build_crate(bm, x=cx - 0.62, y=cy - 0.40, z_ground=0.54, size=0.46, height=0.44)
    build_crate(bm, x=cx + 0.55, y=cy - 0.50, z_ground=0.0, size=0.50, height=0.52, ang=0.15)
    build_barrel(bm, x=cx + 0.62, y=cy + 0.35, z_ground=0.0, ang=0.4, radius=0.31, height=0.70)
    build_barrel(bm, x=cx + 0.10, y=cy + 0.55, z_ground=0.0, ang=1.1, radius=0.28, height=0.64)
    build_clay_pot(bm, x=cx - 0.32, y=cy + 0.52, z_ground=0.0, ang=0.4,
                   radius=0.20, height=0.50, pot_type='JAR')
    build_clay_pot(bm, x=cx + 0.04, y=cy + 0.30, z_ground=0.0, ang=-0.5,
                   radius=0.17, height=0.44, pot_type='URN')


def _awning_on_gable(bm, kind, ox, oy, rot, half_len, side_sign=1.0, **kw):
    """Back a yard shelter onto a building's gable end (local +/-X), like an
    attached lean-to tucked against the wall."""
    nx, ny = math.cos(rot) * side_sign, math.sin(rot) * side_sign
    depth = kw.get('depth', 2.4)
    off = half_len + depth * 0.5 + 0.05
    _build_awning_at(bm, kind, cx=ox + nx * off, cy=oy + ny * off, z_base=0.0,
                     rot_z=rot + side_sign * math.pi * 0.5, **kw)


def _place_estate_awnings(bm, props, tier, spread_x, fore_y, stable=None, servant=None):
    """Rustic yard shelters stocked as private little stores.

    Each is backed against an outbuilding's gable end when that outbuilding exists
    (so they read as attached lean-tos, not floating in the courtyard); otherwise
    they fall back to the open forecourt.
    """
    shelters = (
        ('TARP', stable, -spread_x * 0.55, 'LEANTO', 3.4, 2.8, 2.25, 2.80),
        ('LEANTO', servant, spread_x * 0.55, 'TARP', 2.8, 2.4, 1.95, 2.55),
    )
    for kind, slot, fallback_x, _other, width, depth, fh, bh in shelters:
        if slot is not None:
            ox, oy, rot, olen = slot
            outward = 1.0 if (math.cos(rot) * ox + math.sin(rot) * oy) >= 0.0 else -1.0
            nx, ny = math.cos(rot) * outward, math.sin(rot) * outward
            off = olen * 0.5 + depth * 0.5 + 0.05
            cx, cy = ox + nx * off, oy + ny * off
            aw_rot = rot + outward * math.pi * 0.5
        else:
            cx, cy = fallback_x, fore_y + 4.8
            aw_rot = 0.0 if kind == 'TARP' else math.pi * 0.5
        _build_awning_at(bm, kind, cx=cx, cy=cy, z_base=0.0, rot_z=aw_rot,
                         width=width, depth=depth, front_h=fh, back_h=bh)
        _stock_shelter(bm, cx, cy, 1.0 if cx >= 0.0 else -1.0)


def build_estate_outbuildings(bm, props, ctx):
    """
    High-level orchestrator called during architectural accessories dispatch.
    Places the detached stables, servant quarters, courtyard fountain and awnings
    procedurally according to scene properties.
    """
    tier = getattr(props, 'material_tier', 'TIER_1')
    has_stable = getattr(props, 'has_stable', False)
    has_servants = getattr(props, 'has_servant_quarters', False)
    has_fountain = getattr(props, 'has_estate_fountain', False)
    has_awnings = getattr(props, 'estate_awnings', False)

    if not (has_stable or has_servants or has_fountain or has_awnings):
        return

    spread_x = getattr(props, 'outbuilding_offset_x', 24.0)
    fore_y = getattr(props, 'outbuilding_offset_y', -10.0)
    stable_side = getattr(props, 'stable_side', 'LEFT')
    servant_side = getattr(props, 'servant_quarters_side', 'RIGHT')
    setback = getattr(props, 'plot_setback', 0.0)
    base_hy = ctx.base_d * 0.5

    # 1. Central Courtyard Fountain — centred in the (now deeper) honor court.
    if has_fountain:
        manor_front = setback - base_hy
        fountain_y = (fore_y + manor_front) * 0.5
        fountain_y = min(fountain_y, fore_y + 2.0)
        build_estate_fountain(bm, pos=(0.0, fountain_y, 0.0), tier=tier)

    stable_slot = None
    servant_slot = None

    # 2. Horse Stable & Carriage Barn
    if has_stable:
        st_sgn = -1.0 if stable_side == 'LEFT' else 1.0
        st_x = st_sgn * spread_x
        st_y = fore_y
        # Rotate 90 deg so the carriage door faces the courtyard, not the field.
        # Auto on very wide plots, or whenever the preset explicitly asks for it.
        _rot_on = getattr(props, 'stable_rotate', False) or spread_x > 18.0
        st_rot = -math.pi * 0.5 * st_sgn if _rot_on else 0.0
        build_stable(bm, props, pos=(st_x, st_y, 0.0), rot_z=st_rot, tier=tier)
        stable_slot = (st_x, st_y, st_rot, _stable_dims(tier)[0])

    # 3. Servant Quarters / Steward Lodge
    if has_servants:
        sq_sgn = -1.0 if servant_side == 'LEFT' else 1.0
        sq_x = sq_sgn * spread_x
        sq_y = fore_y
        sq_rot = -math.pi * 0.5 * sq_sgn if spread_x > 18.0 else 0.0
        sq_w = 13.5 if tier == 'TIER_3' else (12.0 if tier == 'TIER_2' else 10.5)
        sq_d = 7.5 if tier == 'TIER_3' else 6.8
        sq_fl = 2 if tier in ('TIER_2', 'TIER_3') else 1
        build_servant_quarters(
            bm, props, pos=(sq_x, sq_y, 0.0), rot_z=sq_rot, tier=tier,
            width=sq_w, depth=sq_d, floors=sq_fl
        )
        servant_slot = (sq_x, sq_y, sq_rot, sq_w)

    # 4. Yard shelters backed onto the outbuilding gables
    if has_awnings:
        _place_estate_awnings(bm, props, tier, spread_x, fore_y,
                              stable=stable_slot, servant=servant_slot)
