schema_version = "1.0.0"

id = "blend_building_creator"
version = "1.7.0"
name = "Stylized Fantasy Building Generator"
tagline = "Generate stylized fantasy buildings with walk-in interiors"
maintainer = "Stylized 3D Studio"
type = "add-on"

# Supported Blender versions
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 Stylized Building Creator",
]
