"""
Architectural style presets for the Stylized Fantasy Building Generator.
Instantly configures dimensions, shapes, roof styles, interior, material tiers, and colors.
Organized into 5 thematic categories:
- Civic & Manor
- Military
- Artisan Guilds
- Industrial & Craft
- Commercial & Living
"""

PRESET_CATEGORIES = [
    ('ALL', "All Presets", "Show all building style presets"),
    ('CIVIC', "Civic & Manor", "Town halls, manors, chapels, and grand inns"),
    ('MILITARY', "Military", "Barracks, archery ranges, and watchtowers"),
    ('ARTISAN', "Artisan Guilds", "Specialized craft shops, bakeries, breweries, and workshops"),
    ('INDUSTRIAL', "Industrial & Craft", "Heavy production, smelteries, mills, and factories"),
    ('COMMERCIAL', "Commercial & Living", "Stores, markets, houses, cottages, and towers"),
]

PRESETS = {
    # --- CIVIC & MANOR ---
    'TOWN_HALL': {
        'category': 'CIVIC',
        'name': "Town Hall",
        'description': "Grand 3-story civic hall with an L-shaped wing, high gable roof, stone foundation, and dormers",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_3',
            'num_floors': 3,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 8.5,
            'depth': 6.2,
            'wing_width': 4.5,
            'wing_depth': 3.8,
            'wing_side': 'RIGHT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.25,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.5,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.22, 0.26, 0.35, 1.0),
            'color_wall_ext': (0.88, 0.85, 0.78, 1.0),
            'color_timber': (0.24, 0.15, 0.09, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'KNIGHTS_MANOR': {
        'category': 'CIVIC',
        'name': "Knights Manor",
        'description': "Stately 3-story T-shaped noble estate with cantilever overhangs, high masonry base, and ornate framing",
        'settings': {
            'building_shape': 'T_SHAPE',
            'material_tier': 'TIER_3',
            'num_floors': 3,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 8.8,
            'depth': 6.0,
            'wing_width': 4.8,
            'wing_depth': 3.6,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'ALL_FLOORS',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.80,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.6,
            'roof_sway': 0.25,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.48, 0.22, 0.15, 1.0),
            'color_wall_ext': (0.90, 0.88, 0.82, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HEALERS_CHAPEL': {
        'category': 'CIVIC',
        'name': "Healers Chapel",
        'description': "Serene stone sanctuary with steep whimsical sway roof, glowing stained lanterns, and high arched entrance",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'num_floors': 2,
            'floor_height': 3.2,
            'width': 6.8,
            'depth': 5.2,
            'wall_thickness': 0.30,
            'has_cantilever': False,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'SPIRAL',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.20,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': False,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'SWAY',
            'roof_height': 3.8,
            'roof_sway': 0.35,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': False,
            'has_chimney': False,
            'color_shingles': (0.20, 0.38, 0.45, 1.0),
            'color_wall_ext': (0.92, 0.90, 0.84, 1.0),
            'color_timber': (0.28, 0.17, 0.10, 1.0),
            'window_glow_strength': 4.0
        }
    },
    'INN': {
        'category': 'CIVIC',
        'name': "Grand Country Inn",
        'description': "Three-story hospitable inn with large taproom, upper guest rooms, double chimney, and flower-filled windows",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_3',
            'num_floors': 3,
            'wing_floors': 2,
            'floor_height': 2.8,
            'width': 8.0,
            'depth': 5.8,
            'wing_width': 4.2,
            'wing_depth': 3.6,
            'wing_side': 'RIGHT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.08,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.0,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.3,
            'roof_sway': 0.30,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.24, 0.32, 0.44, 1.0),
            'color_wall_ext': (0.87, 0.81, 0.72, 1.0),
            'color_timber': (0.25, 0.15, 0.09, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # --- MILITARY ---
    'INFANTRY_BARRACKS': {
        'category': 'MILITARY',
        'name': "Infantry Barracks",
        'description': "Solid two-story rectangular quarters built for garrison housing with sturdy timber framing and stone base",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 8.8,
            'depth': 5.2,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.03,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.0,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.25,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.0,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.28, 0.32, 0.36, 1.0),
            'color_wall_ext': (0.82, 0.76, 0.66, 1.0),
            'color_timber': (0.26, 0.16, 0.10, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'ARCHERY_RANGE': {
        'category': 'MILITARY',
        'name': "Archery Range",
        'description': "Rustic single-story log lodge with deep sheltering eaves, open training entrance, and tool racks",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'num_floors': 1,
            'floor_height': 2.9,
            'width': 7.8,
            'depth': 4.6,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.07,
            'has_foundation': True,
            'foundation_height': 0.40,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.20,
            'door_angle': 45.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 2.8,
            'roof_overhang': 0.65,
            'roof_sway': 0.28,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'color_shingles': (0.26, 0.18, 0.12, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'WATCHTOWER': {
        'category': 'MILITARY',
        'name': "Lookout Watchtower",
        'description': "Fortified 3-story stone beacon tower with wooden upper lookout platform and slate gable roof",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'num_floors': 3,
            'floor_height': 3.0,
            'width': 4.6,
            'depth': 4.6,
            'wall_thickness': 0.32,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.90,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'SPIRAL',
            'stair_width': 0.88,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 0.95,
            'door_angle': 15.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 2.6,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': False,
            'color_shingles': (0.26, 0.28, 0.30, 1.0),
            'color_wall_ext': (0.84, 0.80, 0.72, 1.0),
            'color_timber': (0.22, 0.14, 0.08, 1.0),
            'window_glow_strength': 0.0
        }
    },

    # --- ARTISAN GUILDS ---
    'ARTISAN_BAKERY': {
        'category': 'ARTISAN',
        'name': "Artisan Bakery",
        'description': "Warm 2-story bakery with a 1-story attached hearth oven wing and tall smoking stone chimney",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 6.8,
            'depth': 5.0,
            'wing_width': 3.4,
            'wing_depth': 3.0,
            'wing_side': 'RIGHT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.08,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.92,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.10,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.0,
            'roof_sway': 0.26,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.50, 0.25, 0.18, 1.0),
            'color_wall_ext': (0.86, 0.80, 0.70, 1.0),
            'color_timber': (0.30, 0.18, 0.10, 1.0),
            'window_glow_strength': 3.0
        }
    },
    'ARTISAN_TAILOR': {
        'category': 'ARTISAN',
        'name': "Artisan Tailor",
        'description': "Charming boutique workshop with floral window boxes, display shutters, and living quarters above",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 6.2,
            'depth': 4.8,
            'wall_thickness': 0.26,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.07,
            'has_foundation': True,
            'foundation_height': 0.50,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.90,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.1,
            'roof_sway': 0.28,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.25, 0.36, 0.48, 1.0),
            'color_wall_ext': (0.88, 0.82, 0.74, 1.0),
            'color_timber': (0.28, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'ARTISAN_TOOLSMITH': {
        'category': 'ARTISAN',
        'name': "Artisan Toolsmith",
        'description': "Sturdy craftsman workshop with a 1-story grinding annex, wide timber portal, and anvil hearth",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 7.0,
            'depth': 5.2,
            'wing_width': 3.6,
            'wing_depth': 3.0,
            'wing_side': 'LEFT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.07,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_angle': 40.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.28, 0.30, 0.32, 1.0),
            'color_wall_ext': (0.83, 0.77, 0.67, 1.0),
            'color_timber': (0.24, 0.15, 0.09, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'ARTISAN_JEWELER': {
        'category': 'ARTISAN',
        'name': "Artisan Jeweler",
        'description': "Refined two-story townhouse with reinforced ashlar vault base, delicate upper timbering, and glowing lanterns",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'num_floors': 2,
            'floor_height': 2.9,
            'width': 5.8,
            'depth': 4.6,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'SPIRAL',
            'stair_width': 0.90,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.2,
            'roof_sway': 0.26,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.22, 0.28, 0.40, 1.0),
            'color_wall_ext': (0.90, 0.88, 0.82, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'ARTISAN_BREWERY': {
        'category': 'ARTISAN',
        'name': "Artisan Brewery",
        'description': "Substantial T-shaped brewhouse with deep stone fermenting cellars and broad mash-tun wings",
        'settings': {
            'building_shape': 'T_SHAPE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 8.2,
            'depth': 5.6,
            'wing_width': 4.2,
            'wing_depth': 3.4,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.07,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.0,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.25,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.4,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.42, 0.24, 0.16, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.28, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'ARTISAN_FISHER': {
        'category': 'ARTISAN',
        'name': "Artisan Fisher",
        'description': "Single-story coastal log shack with wide sheltering eaves, stone drying steps, and rustic timbering",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'num_floors': 1,
            'floor_height': 2.7,
            'width': 5.6,
            'depth': 4.2,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.10,
            'has_foundation': True,
            'foundation_height': 0.50,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_angle': 40.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 2.8,
            'roof_overhang': 0.60,
            'roof_sway': 0.32,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'color_shingles': (0.28, 0.20, 0.14, 1.0),
            'color_wall_ext': (0.35, 0.24, 0.15, 1.0),
            'color_timber': (0.22, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'ARTISAN_FURNITURE_MAKER': {
        'category': 'ARTISAN',
        'name': "Artisan Furniture Maker",
        'description': "Spacious carpenter's shop with an attached 1-story timber seasoning wing and double lumber doors",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 7.4,
            'depth': 5.2,
            'wing_width': 3.8,
            'wing_depth': 3.2,
            'wing_side': 'RIGHT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.0,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_angle': 40.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.34, 0.28, 0.22, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'ARTISAN_BUTCHER': {
        'category': 'ARTISAN',
        'name': "Artisan Butcher",
        'description': "Solid 2-story building with high stone foundation, 1-story cool-storage annex, and sturdy meat hooks",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 6.6,
            'depth': 5.0,
            'wing_width': 3.4,
            'wing_depth': 2.8,
            'wing_side': 'LEFT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.0,
            'roof_sway': 0.25,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.30, 0.34, 0.38, 1.0),
            'color_wall_ext': (0.85, 0.80, 0.72, 1.0),
            'color_timber': (0.28, 0.17, 0.10, 1.0),
            'window_glow_strength': 1.5
        }
    },

    # --- INDUSTRIAL & CRAFT ---
    'BLACKSMITH': {
        'category': 'INDUSTRIAL',
        'name': "Village Blacksmith",
        'description': "Two-story smithy with 1-story forge annex, heavy stone chimney, and wide tool portal",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 6.8,
            'depth': 5.2,
            'wing_width': 3.6,
            'wing_depth': 3.2,
            'wing_side': 'RIGHT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.07,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.20,
            'door_angle': 50.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.0,
            'roof_sway': 0.28,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'color_shingles': (0.24, 0.26, 0.28, 1.0),
            'color_wall_ext': (0.82, 0.76, 0.68, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'INDUSTRIAL_WEAPON_SMITH': {
        'category': 'INDUSTRIAL',
        'name': "Industrial Weapon Smith",
        'description': "Heavy dual-chimney armory forge with 1-story grinding annex and reinforced ashlar stone masonry",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_3',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 7.6,
            'depth': 5.5,
            'wing_width': 3.8,
            'wing_depth': 3.4,
            'wing_side': 'LEFT',
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.0,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.3,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.22, 0.24, 0.26, 1.0),
            'color_wall_ext': (0.86, 0.82, 0.74, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 3.0
        }
    },
    'INDUSTRIAL_ARMOR_SMITH': {
        'category': 'INDUSTRIAL',
        'name': "Industrial Armor Smith",
        'description': "Expansive T-shaped foundry with heavy blast furnaces, quenching vats, and solid stone lower works",
        'settings': {
            'building_shape': 'T_SHAPE',
            'material_tier': 'TIER_3',
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 3.0,
            'width': 8.2,
            'depth': 5.8,
            'wing_width': 4.4,
            'wing_depth': 3.6,
            'wall_thickness': 0.32,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.80,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.35,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.4,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.20, 0.22, 0.25, 1.0),
            'color_wall_ext': (0.84, 0.80, 0.72, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'INDUSTRIAL_WEAVING_MILL': {
        'category': 'INDUSTRIAL',
        'name': "Industrial Weaving Mill",
        'description': "Long 2-story textile mill with high natural lighting from rhythmic windows and clean plank cladding",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 9.5,
            'depth': 5.2,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.0,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.20,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': False,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.32, 0.38, 0.44, 1.0),
            'color_wall_ext': (0.85, 0.79, 0.69, 1.0),
            'color_timber': (0.28, 0.17, 0.10, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'INDUSTRIAL_SMELTERY': {
        'category': 'INDUSTRIAL',
        'name': "Industrial Smeltery / Foundry",
        'description': "Massive thermal smelting facility with towering stone chimney stacks and heat-venting dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'num_floors': 2,
            'floor_height': 3.2,
            'width': 8.6,
            'depth': 6.0,
            'wall_thickness': 0.34,
            'has_cantilever': False,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.85,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.40,
            'door_angle': 15.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.5,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.20, 0.20, 0.22, 1.0),
            'color_wall_ext': (0.80, 0.76, 0.70, 1.0),
            'color_timber': (0.18, 0.11, 0.06, 1.0),
            'window_glow_strength': 4.5
        }
    },
    'INDUSTRIAL_TANNERY': {
        'category': 'INDUSTRIAL',
        'name': "Industrial Tannery",
        'description': "Rustic riverbank leatherworking facility with heavy log framing and slatted drying levels",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'num_floors': 2,
            'floor_height': 2.7,
            'width': 7.6,
            'depth': 5.0,
            'wall_thickness': 0.26,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.08,
            'has_foundation': True,
            'foundation_height': 0.50,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.20,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 2.9,
            'roof_sway': 0.28,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'color_shingles': (0.30, 0.22, 0.16, 1.0),
            'color_wall_ext': (0.36, 0.25, 0.16, 1.0),
            'color_timber': (0.24, 0.15, 0.09, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'INDUSTRIAL_WINDMILL': {
        'category': 'INDUSTRIAL',
        'name': "Industrial Windmill Base",
        'description': "Tall 4-story round masonry mill tower with conical turret roof and interior spiral staircase",
        'settings': {
            'building_shape': 'ROUND_TOWER',
            'material_tier': 'TIER_3',
            'num_floors': 4,
            'floor_height': 2.9,
            'width': 5.2,
            'depth': 5.2,
            'wall_thickness': 0.32,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.25,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.85,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'SPIRAL',
            'stair_width': 0.90,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.10,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'TURRET',
            'roof_height': 3.6,
            'has_roof_shingles': False,
            'has_dormers': False,
            'has_chimney': False,
            'color_wall_ext': (0.88, 0.84, 0.76, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'INDUSTRIAL_FURNITURE_FACTORY': {
        'category': 'INDUSTRIAL',
        'name': "Industrial Furniture Factory",
        'description': "Large 2-story dual-wing manufacturing plant with expansive assembly bays and timber loading docks",
        'settings': {
            'building_shape': 'T_SHAPE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 2.9,
            'width': 9.0,
            'depth': 6.0,
            'wing_width': 4.6,
            'wing_depth': 3.8,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.35,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.5,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.34, 0.28, 0.22, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.0
        }
    },

    # --- COMMERCIAL & LIVING ---
    'WAREHOUSE': {
        'category': 'COMMERCIAL',
        'name': "Commercial Warehouse",
        'description': "High-capacity 2-story storage depot with wide double cargo doors, robust timber posts, and slate gable",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'floor_height': 3.0,
            'width': 9.2,
            'depth': 6.2,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.03,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.50,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': False,
            'color_shingles': (0.28, 0.32, 0.38, 1.0),
            'color_wall_ext': (0.82, 0.77, 0.68, 1.0),
            'color_timber': (0.25, 0.15, 0.09, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'MARKET': {
        'category': 'COMMERCIAL',
        'name': "Covered Market Pavilion",
        'description': "Open rustic trade hall with wide timber overhangs, multiple display windows, and welcoming lanterns",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'num_floors': 1,
            'floor_height': 2.9,
            'width': 7.6,
            'depth': 5.0,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.07,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_angle': 50.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.0,
            'roof_overhang': 0.65,
            'roof_sway': 0.30,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': False,
            'color_shingles': (0.32, 0.22, 0.15, 1.0),
            'color_wall_ext': (0.36, 0.24, 0.16, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'GENERAL_STORE': {
        'category': 'COMMERCIAL',
        'name': "General Store",
        'description': "Inviting 2-story emporium with colorful storefront, deep flowerboxes, and living quarters above",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 6.6,
            'depth': 5.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.1,
            'roof_sway': 0.28,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.24, 0.34, 0.46, 1.0),
            'color_wall_ext': (0.87, 0.81, 0.72, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 3.0
        }
    },
    'HUNTERS_HUT': {
        'category': 'COMMERCIAL',
        'name': "Hunters Log Hut",
        'description': "Rustic 1-story log cabin with heavy fieldstone chimney, warm lanterns, and deep wooden eaves",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'num_floors': 1,
            'floor_height': 2.7,
            'width': 5.2,
            'depth': 4.2,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.11,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.0,
            'door_angle': 40.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 2.7,
            'roof_overhang': 0.60,
            'roof_sway': 0.32,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'color_shingles': (0.26, 0.18, 0.12, 1.0),
            'color_wall_ext': (0.32, 0.20, 0.12, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'COTTAGE': {
        'category': 'COMMERCIAL',
        'name': "Fairytale Cottage",
        'description': "Picturesque 1.5-story home with extreme saddle roof sway, cozy dormers, flower boxes, and stone chimney",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'num_floors': 1,
            'floor_height': 2.7,
            'width': 5.4,
            'depth': 4.2,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.12,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.0,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.2,
            'roof_overhang': 0.55,
            'roof_sway': 0.40,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.20, 0.35, 0.45, 1.0),
            'color_wall_ext': (0.89, 0.84, 0.75, 1.0),
            'color_timber': (0.26, 0.15, 0.09, 1.0),
            'window_glow_strength': 3.0
        }
    },
    'TOWNHOUSE': {
        'category': 'COMMERCIAL',
        'name': "Medieval Townhouse",
        'description': "Tall 3-story urban residence with progressive overhangs, steep gable roof, and Tudor half-timbering",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'num_floors': 3,
            'floor_height': 2.8,
            'width': 5.8,
            'depth': 5.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'ALL_FLOORS',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.6,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.24, 0.26, 0.28, 1.0),
            'color_wall_ext': (0.85, 0.78, 0.68, 1.0),
            'color_timber': (0.22, 0.14, 0.08, 1.0),
            'window_glow_strength': 0.0
        }
    },
    'TAVERN': {
        'category': 'COMMERCIAL',
        'name': "Cozy Fantasy Tavern",
        'description': "Two-story L-shaped inn with rustic ceiling beams, stone foundation, sway roof, and lanterns",
        'settings': {
            'building_shape': 'L_SHAPE',
            'material_tier': 'TIER_3',
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 2.8,
            'width': 7.2,
            'depth': 5.4,
            'wing_width': 3.8,
            'wing_depth': 3.2,
            'wing_side': 'RIGHT',
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.08,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_angle': 40.0,
            'has_windows': True,
            'has_shutters': True,
            'has_flower_boxes': True,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.2,
            'roof_sway': 0.32,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'color_shingles': (0.18, 0.28, 0.46, 1.0),
            'color_wall_ext': (0.88, 0.82, 0.72, 1.0),
            'color_timber': (0.28, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'WIZARD_TOWER': {
        'category': 'COMMERCIAL',
        'name': "Wizard / Alchemist Tower",
        'description': "Tall 3-story round tower with conical turret spire roof, spiral staircase, and crooked chimney",
        'settings': {
            'building_shape': 'ROUND_TOWER',
            'material_tier': 'TIER_3',
            'num_floors': 3,
            'floor_height': 3.0,
            'width': 4.6,
            'depth': 4.6,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.25,
            'wonkiness': 0.11,
            'has_foundation': True,
            'foundation_height': 0.8,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'SPIRAL',
            'stair_width': 0.90,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.0,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': False,
            'has_flower_boxes': False,
            'has_lanterns': True,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'TURRET',
            'roof_height': 4.2,
            'has_roof_shingles': False,
            'has_dormers': False,
            'has_chimney': True,
            'color_wall_ext': (0.86, 0.82, 0.75, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 4.0
        }
    }
}

def apply_preset(props, preset_key):
    """Applies preset dictionary values to the PropertyGroup."""
    if preset_key not in PRESETS:
        return
        
    data = PRESETS[preset_key]['settings']
    # Temporarily disable auto_update during batch assignment to avoid multiple regenerations
    old_auto = props.auto_update
    props.auto_update = False
    
    for k, v in data.items():
        if hasattr(props, k):
            setattr(props, k, v)
            
    props.auto_update = old_auto
