"""
Purpose-built architectural style presets for Stylized Fantasy Buildings.
Strictly calibrated to plot sizes (12m x 12m, 20m x 20m, 12m x 20m, and 40m x 40m).

Catalog:
- Town Hall (T-shaped, T1-T3) [Plot: 40m x 40m]
- Warehouse (L-shaped, T1-T3) [Plot: 20m x 20m, courtyard crane, no hook]
- Lumbermill (L-shaped, T1-T3) [Plot: 20m x 20m, all open timber frame, expanding T1-T3]
- Infantry Barracks (U-shaped, T1-T3) [Plot: 40m x 40m]
- House 1 Small (Square, T1-T3) [Plot: 12m x 12m]
- House 2 Small (Square variant, T1-T3) [Plot: 12m x 12m]
- House 1 Medium (Square, T1-T3) [Plot: 20m x 20m]
- House 2 Medium (Rectangular narrow, T1-T3) [Plot: 12m x 20m]
- House 3 Medium (L-shaped, T1-T3) [Plot: 20m x 20m with 10m x 10m cutout]
- Tavern (T1-T3) [Plot: 20m x 20m, public house / taproom]
- Tavern Long (T1-T3) [Plot: 12m x 20m, long narrow roadside pub]
- Inn (T1-T3) [Plot: 40m x 40m, accommodation + pub]
"""

PRESET_CATEGORIES = [
    ('ALL', "All Presets", "Show all building style presets"),
    ('CIVIC', "Civic", "Town halls and civic estates"),
    ('MILITARY', "Military", "Barracks and military quarters"),
    ('INDUSTRIAL', "Industrial", "Warehouses, storage, and lumbermills"),
    ('RESIDENTIAL', "Residential", "Houses, cottages, and town residences"),
    ('HOSPITALITY', "Hospitality", "Taverns, inns, and wayside hostelries"),
]

PRESETS = {
    # =========================================================================
    # CIVIC: TOWN HALL (T-Shaped, Plot: 40m x 40m)
    # =========================================================================
    'TOWN_HALL_T1': {
        'category': 'CIVIC',
        'family': 'TOWN_HALL',
        'tier': 1,
        'name': "Town Hall (Tier 1)",
        'plot': "40m x 40m",
        'description': "Quirky little log moot-hall: big plank door, stone porch, log colonnade and a small clock spire on the sway roof.",
        'settings': {
            'building_shape': 'T_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 12.5,
            'depth': 8.5,
            'wing_width': 6.5,
            'wing_depth': 5.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.50,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.70,
            'door_height': 2.50,
            'door_angle': 0.0,
            'roof_orientation': 'AUTO',
            'door_shape': 'SQUARE',
            'has_back_door': False,
            'has_side_door': False,
            'side_door_facade': 'RIGHT',
            'has_windows': True,
            'window_spacing': 2.4,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.8,
            'roof_sway': 0.32,
            'roof_flare': 0.40,
            'roof_overhang': 0.82,
            'wing_roof_scale': 0.78,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': False,
            'dormer_count': 2,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': False,
            'wing_dormer_count': 1,
            'has_roof_turret': False,
            'roof_turret_style': 'OCTAGONAL',
            'roof_turret_pos_x': 0.0,
            'roof_turret_pos_y': -0.20,
            'roof_turret_scale': 1.0,
            'has_roof_clock_spire': True,
            'roof_clock_scale': 0.80,
            'roof_clock_pos_x': 0.0,
            'roof_clock_pos_y': -0.20,
            'has_chimney': True,
            'chimney_pos_x': 0.55,
            'chimney_pos_y': 0.55,
            'has_hoist_beam': False,
            'has_loft_hatch': False,
            'has_mini_wing': True,
            'mini_wing_width': 2.4,
            'mini_wing_depth': 1.8,
            'mini_wing_roof': 'LEAN_TO',
            'has_balcony': True,
            'balcony_side': 'FRONT',
            'balcony_mode': 'SINGLE',
            'balcony_floor': 2,
            'balcony_width': 3.0,
            'balcony_depth': 1.3,
            'has_pillared_overhang': True,
            'pillared_overhang_side': 'LEFT',
            'pillared_overhang_depth': 1.6,
            'pillared_overhang_pillars': 3,
            'pillared_overhang_style': 'ROUND_POST',
            'has_clock_tower': False,
            'clock_tower_side': 'RIGHT',
            'clock_tower_size': 2.8,
            'has_corner_turrets': False,
            'corner_turret_size': 1.35,
            'has_arched_porch': True,
            'has_entry_ramp': False,
            'has_side_rampart': False,
            'rampart_side': 'RIGHT',
            'town_hall_composer': True,
            'has_side_annex': False,
            'annex_floors': 1,
            'color_shingles': (0.62, 0.30, 0.13, 1.0),
            'color_wall_ext': (0.36, 0.24, 0.15, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'TOWN_HALL_T2': {
        'category': 'CIVIC',
        'family': 'TOWN_HALL',
        'tier': 2,
        'name': "Town Hall (Tier 2)",
        'plot': "40m x 40m",
        'description': "Grown plank civic hall: 3 storeys, second side entrance, bigger roof clock, new side annex and colonnade under the oriel.",
        'settings': {
            'building_shape': 'T_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 3,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 18.0,
            'depth': 10.5,
            'wing_width': 8.5,
            'wing_depth': 7.0,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.20,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.80,
            'door_height': 2.60,
            'door_angle': 0.0,
            'roof_orientation': 'AUTO',
            'door_shape': 'ARCHED',
            'has_back_door': False,
            'has_side_door': True,
            'side_door_facade': 'RIGHT',
            'has_windows': True,
            'window_spacing': 2.2,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 4.5,
            'roof_sway': 0.25,
            'roof_flare': 0.38,
            'roof_overhang': 0.70,
            'wing_roof_scale': 0.80,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_dormers': True,
            'dormer_count': 3,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': True,
            'wing_dormer_count': 1,
            'wing_dormer_sides': 'BOTH',
            'has_roof_turret': False,
            'roof_turret_style': 'OCTAGONAL',
            'roof_turret_pos_x': 0.0,
            'roof_turret_pos_y': -0.20,
            'roof_turret_scale': 1.25,
            'has_roof_clock_spire': True,
            'roof_clock_scale': 1.10,
            'roof_clock_pos_x': 0.0,
            'roof_clock_pos_y': -0.20,
            'has_chimney': True,
            'chimney_pos_x': 0.55,
            'chimney_pos_y': 0.55,
            'has_hoist_beam': False,
            'has_loft_hatch': False,
            'has_mini_wing': True,
            'mini_wing_width': 2.6,
            'mini_wing_depth': 1.8,
            'mini_wing_roof': 'GABLE',
            'has_balcony': True,
            'balcony_side': 'FRONT',
            'balcony_mode': 'ALL_UPPER',
            'balcony_floor': 2,
            'balcony_width': 3.6,
            'balcony_depth': 1.4,
            'has_pillared_overhang': True,
            'pillared_overhang_side': 'RIGHT',
            'pillared_overhang_depth': 1.8,
            'pillared_overhang_pillars': 4,
            'pillared_overhang_style': 'TIMBER_STONE',
            'has_clock_tower': False,
            'clock_tower_side': 'RIGHT',
            'clock_tower_size': 3.4,
            'has_corner_turrets': False,
            'corner_turret_size': 1.35,
            'has_arched_porch': True,
            'has_entry_ramp': False,
            'has_side_rampart': False,
            'rampart_side': 'RIGHT',
            'town_hall_composer': True,
            'has_side_annex': True,
            'annex_floors': 2,
            'color_shingles': (0.58, 0.24, 0.12, 1.0),
            'color_wall_ext': (0.88, 0.83, 0.73, 1.0),
            'color_timber': (0.23, 0.13, 0.07, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'TOWN_HALL_T3': {
        'category': 'CIVIC',
        'family': 'TOWN_HALL',
        'tier': 3,
        'name': "Town Hall (Tier 3)",
        'plot': "40m x 40m",
        'description': "Great hall of additions: arch-passage clock tower, big corner spires, side rampart walk with upper door, annex and oriels. Ramp climbs the side, not the front.",
        'settings': {
            'building_shape': 'T_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 3,
            'wing_floors': 2,
            'floor_height': 3.1,
            'width': 24.0,
            'depth': 12.5,
            'wing_width': 10.5,
            'wing_depth': 8.5,
            'wall_thickness': 0.32,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.40,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.90,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.30,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.00,
            'door_height': 2.80,
            'door_angle': 0.0,
            'roof_orientation': 'AUTO',
            'door_shape': 'ARCHED',
            'has_back_door': False,
            'has_side_door': False,
            'side_door_facade': 'RIGHT',
            'has_windows': True,
            'window_spacing': 2.2,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 5.0,
            'roof_sway': 0.22,
            'roof_flare': 0.38,
            'roof_overhang': 0.75,
            'wing_roof_scale': 0.82,
            'has_roof_shingles': True,
            'shingle_rows': 10,
            'has_dormers': True,
            'dormer_count': 4,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': True,
            'wing_dormer_count': 2,
            'wing_dormer_sides': 'BOTH',
            'has_roof_turret': False,
            'roof_turret_style': 'OCTAGONAL',
            'roof_turret_pos_x': 0.0,
            'roof_turret_pos_y': -0.10,
            'roof_turret_scale': 1.65,
            'has_roof_clock_spire': False,
            'roof_clock_scale': 1.10,
            'roof_clock_pos_x': 0.0,
            'roof_clock_pos_y': -0.20,
            'has_chimney': True,
            'chimney_pos_x': 0.55,
            'chimney_pos_y': 0.55,
            'has_hoist_beam': False,
            'has_loft_hatch': False,
            'has_mini_wing': True,
            'mini_wing_width': 3.0,
            'mini_wing_depth': 2.0,
            'mini_wing_roof': 'GABLE',
            'has_balcony': True,
            'balcony_side': 'FRONT',
            'balcony_mode': 'ALL_UPPER',
            'balcony_floor': 2,
            'balcony_width': 4.2,
            'balcony_depth': 1.5,
            'has_pillared_overhang': False,
            'pillared_overhang_side': 'RIGHT',
            'pillared_overhang_depth': 2.0,
            'pillared_overhang_pillars': 4,
            'pillared_overhang_style': 'TIMBER_STONE',
            'has_clock_tower': True,
            'clock_tower_side': 'RIGHT',
            'clock_tower_size': 3.6,
            'has_corner_turrets': True,
            'corner_turret_size': 1.65,
            'has_arched_porch': True,
            'has_entry_ramp': False,
            'has_side_rampart': True,
            'rampart_side': 'RIGHT',
            'town_hall_composer': True,
            'has_side_annex': True,
            'annex_floors': 2,
            'color_shingles': (0.55, 0.22, 0.11, 1.0),
            'color_wall_ext': (0.90, 0.87, 0.80, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # INDUSTRIAL: WAREHOUSE (L-Shaped, Plot: 20m x 20m, Courtyard Crane, No Hook)
    # =========================================================================
    'WAREHOUSE_T1': {
        'category': 'INDUSTRIAL',
        'family': 'WAREHOUSE',
        'tier': 1,
        'name': "Warehouse (Tier 1)",
        'plot': "20m x 20m",
        'description': "L-shaped open timber storage depot with heavy pillars and roof only (NO walls), equipped with courtyard swivel crane",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': True,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 3.6,
            'width': 12.0,
            'depth': 6.5,
            'wing_width': 5.5,
            'wing_depth': 5.5,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.40,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.2,
            'roof_overhang': 0.55,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.34, 0.22, 0.15, 1.0),
            'color_wall_ext': (0.35, 0.24, 0.15, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'WAREHOUSE_T2': {
        'category': 'INDUSTRIAL',
        'family': 'WAREHOUSE',
        'tier': 2,
        'name': "Warehouse (Tier 2)",
        'plot': "20m x 20m",
        'description': "Enclosed two-storey L-shaped cargo warehouse with solid walls, wide freight portals, dormers, and courtyard swivel crane",
        'settings': {
            'has_loft_hatch': True,
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 3.4,
            'width': 13.5,
            'depth': 7.0,
            'wing_width': 6.2,
            'wing_depth': 6.2,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.20,
            'door_height': 2.50,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.6,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.28, 0.32, 0.38, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.25, 0.15, 0.09, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'WAREHOUSE_T3': {
        'category': 'INDUSTRIAL',
        'family': 'WAREHOUSE',
        'tier': 3,
        'name': "Warehouse (Tier 3)",
        'plot': "20m x 20m",
        'description': "Expansive two-storey L-shaped trade depot with dual full-height wings, stone base, upper overhang, and heavy courtyard crane",
        'settings': {
            'has_loft_hatch': True,
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 3.6,
            'width': 15.5,
            'depth': 7.8,
            'wing_width': 7.0,
            'wing_depth': 7.2,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.15,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.40,
            'door_height': 2.70,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 4.0,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.24, 0.28, 1.0),
            'color_wall_ext': (0.88, 0.84, 0.76, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 2.0
        }
    },

    # =========================================================================
    # INDUSTRIAL: LUMBERMILL (Rectangular, Plot: 20m x 20m, All Open Pillars/Roof)
    # =========================================================================
    'LUMBERMILL_T1': {
        'category': 'INDUSTRIAL',
        'family': 'LUMBERMILL',
        'tier': 1,
        'name': "Lumbermill (Tier 1)",
        'plot': "20m x 20m",
        'description': "Rustic open sawmill pavilion with creature treadwheel driving a single circular saw bench and a ground log pile, NO walls",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'mill_grade': 'GRADE_1',
            'open_timber_frame': True,
            'num_floors': 1,
            'floor_height': 3.6,
            'width': 12.0,
            'depth': 7.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.35,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.2,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.34, 0.22, 0.15, 1.0),
            'color_wall_ext': (0.35, 0.24, 0.15, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'LUMBERMILL_T2': {
        'category': 'INDUSTRIAL',
        'family': 'LUMBERMILL',
        'tier': 2,
        'name': "Lumbermill (Tier 2)",
        'plot': "20m x 20m",
        'description': "Plank-clad open mill with geared treadwheel, chain drive, rail carriage, mini indoor crane and yard crane, NO walls",
        'settings': {
            'has_loft_hatch': True,
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'mill_grade': 'GRADE_2',
            'open_timber_frame': True,
            'num_floors': 1,
            'floor_height': 3.8,
            'width': 13.0,
            'depth': 7.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.5,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.28, 0.32, 0.38, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'LUMBERMILL_T3': {
        'category': 'INDUSTRIAL',
        'family': 'LUMBERMILL',
        'tier': 3,
        'name': "Lumbermill (Tier 3)",
        'plot': "20m x 20m",
        'description': "Stone-dressed milling hall with great treadwheel, roller infeed, indoor crane and full courtyard crane, NO walls",
        'settings': {
            'has_loft_hatch': True,
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'mill_grade': 'GRADE_3',
            'open_timber_frame': True,
            'num_floors': 1,
            'floor_height': 4.0,
            'width': 14.5,
            'depth': 9.0,
            'wall_thickness': 0.30,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.8,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.24, 0.28, 1.0),
            'color_wall_ext': (0.88, 0.84, 0.76, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 1.0
        }
    },

    # =========================================================================
    # MILITARY: INFANTRY BARRACKS (U-Shaped, Plot: 40m x 40m)
    # =========================================================================
    'INFANTRY_BARRACKS_T1': {
        'category': 'MILITARY',
        'family': 'INFANTRY_BARRACKS',
        'tier': 1,
        'name': "Infantry Barracks (Tier 1)",
        'plot': "40m x 40m",
        'description': "Single-storey U-shaped log garrison camp: twin wings around a drill courtyard, timber gate and a stone arched entry porch.",
        'settings': {
            'building_shape': 'U_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 18.5,
            'depth': 7.0,
            'wing_depth': 6.5,
            'wing_width': 3.8,
            'courtyard_width': 8.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.50,
            'door_height': 2.30,
            'door_angle': 0.0,
            'door_shape': 'SQUARE',
            'has_windows': True,
            'has_shutters': True,
            'shutter_state': 'OPEN',

            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.2,
            'roof_overhang': 0.55,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'has_loft_hatch': False,
            'has_arched_porch': True,
            'has_palisade': True,
            'palisade_style': 'STAKES',
            'palisade_height': 2.4,
            'palisade_offset': 3.8,
            'has_banners': True,
            'banner_count': 2,
            'has_military_props': True,
            'military_props_count': 2,
            'military_rack_count': 1,
            'military_dummy_count': 2,
            'military_target_count': 2,
            'color_shingles': (0.34, 0.24, 0.16, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'color_stone': (0.40, 0.39, 0.37, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'INFANTRY_BARRACKS_T2': {
        'category': 'MILITARY',
        'family': 'INFANTRY_BARRACKS',
        'tier': 2,
        'name': "Infantry Barracks (Tier 2)",
        'plot': "40m x 40m",
        'description': "Two-storey U-shaped plank headquarters with a stone plinth, mounted round shields, side rampart walk, kite-shield gable crest and drill yard.",
        'settings': {
            'building_shape': 'U_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 25.0,
            'depth': 8.5,
            'wing_depth': 8.0,
            'wing_width': 4.2,
            'courtyard_width': 9.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.80,
            'door_height': 2.50,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'has_shutters': True,
            'shutter_state': 'OPEN',

            'has_timber_framing': True,
            'timber_diagonals': True,
            'physical_siding': True,
            'plank_direction': 'VERTICAL',
            'plank_jankiness': 0.30,
            'stone_block_scale': 1.10,
            'stone_disorder': 0.40,
            'has_exposed_brick': True,
            'exposed_brick_frequency': 0.20,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.6,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'dormer_count': 2,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': True,
            'wing_dormer_count': 1,
            'wing_dormer_sides': 'BOTH',
            'has_chimney': True,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'has_mini_wing': True,
            'mini_wing_count': 3,
            'mini_wing_width': 2.2,
            'mini_wing_depth': 1.6,
            'mini_wing_roof': 'GABLE',
            'mini_wing_random': True,
            'mini_wing_random_size': True,
            'has_arched_porch': True,
            'has_side_rampart': True,
            'rampart_side': 'RIGHT',
            'has_palisade': True,
            'palisade_style': 'PICKET',
            'palisade_height': 2.3,
            'palisade_offset': 3.8,
            'has_mounted_shields': True,
            'shield_placement': 'ALL',
            'has_gable_crest': True,
            'gable_crest_style': 'KITE_SHIELD',
            'has_banners': True,
            'banner_count': 3,
            'has_battlements': True,
            'battlement_style': 'TIMBER',
            'has_military_props': True,
            'military_props_count': 3,
            'military_rack_count': 2,
            'military_dummy_count': 2,
            'military_target_count': 2,
            'color_shingles': (0.26, 0.30, 0.38, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'color_stone': (0.42, 0.42, 0.40, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'INFANTRY_BARRACKS_T3': {
        'category': 'MILITARY',
        'family': 'INFANTRY_BARRACKS',
        'tier': 3,
        'name': "Infantry Barracks (Tier 3)",
        'plot': "40m x 40m",
        'description': "Fortified citadel garrison: stone-clad wings around the muster yard, a crenellated stone curtain wall and gatehouse, a side rampart walk with its long descent ramp, flared corner bastion towers with real arrow slits, kite-shield crest and roof spire.",
        'settings': {
            'building_shape': 'U_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 27.0,
            'depth': 9.5,
            'wing_depth': 9.0,
            'wing_width': 4.5,
            'courtyard_width': 9.0,
            'wall_thickness': 0.32,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.85,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.20,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.00,
            'door_height': 2.60,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'has_shutters': True,
            'shutter_state': 'OPEN',

            'has_timber_framing': True,
            'timber_diagonals': True,
            'physical_siding': True,
            'stone_block_scale': 1.25,
            'stone_disorder': 0.50,
            'has_exposed_brick': True,
            'exposed_brick_frequency': 0.20,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 4.2,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_dormers': True,
            'dormer_count': 3,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': True,
            'wing_dormer_count': 1,
            'wing_dormer_sides': 'BOTH',
            'has_chimney': True,
            'has_roof_turret': True,
            'roof_turret_style': 'SQUARE',
            'roof_turret_pos_x': 0.0,
            'roof_turret_pos_y': -0.15,
            'roof_turret_scale': 1.20,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'has_clock_tower': False,
            'clock_tower_side': 'RIGHT',
            'clock_tower_size': 3.6,
            'has_corner_turrets': True,
            'corner_turret_size': 1.65,
            'has_arched_porch': True,
            'has_side_rampart': True,
            'rampart_side': 'RIGHT',
            'has_bastion_towers': True,
            'bastion_tower_count': 2,
            'bastion_tower_size': 3.4,
            'bastion_tower_height': 8.5,
            'has_curtain_wall': True,
            'curtain_wall_height': 3.4,
            'curtain_wall_thickness': 0.60,
            'curtain_wall_offset': 5.5,
            'curtain_wall_depth_extra': 1.5,
            'has_palisade': False,
            'palisade_style': 'STAKES',
            'palisade_height': 2.2,
            'palisade_offset': 3.8,
            'has_mounted_shields': True,
            'shield_placement': 'ALL',
            'has_gable_crest': True,
            'gable_crest_style': 'KITE_SHIELD',
            'has_banners': True,
            'banner_count': 4,
            'has_battlements': True,
            'battlement_style': 'STONE',
            'has_military_props': True,
            'military_props_count': 3,
            'military_rack_count': 2,
            'military_dummy_count': 3,
            'military_target_count': 3,
            'has_mini_wing': True,
            'mini_wing_count': 4,
            'mini_wing_width': 2.4,
            'mini_wing_depth': 1.8,
            'mini_wing_roof': 'GABLE',
            'mini_wing_random': True,
            'mini_wing_random_size': True,
            'color_shingles': (0.44, 0.16, 0.11, 1.0),
            'color_wall_ext': (0.80, 0.78, 0.72, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'color_stone': (0.44, 0.44, 0.42, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 1 SMALL (Square, Plot: 12m x 12m)
    # =========================================================================
    'HOUSE_1_SMALL_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_SMALL',
        'tier': 1,
        'name': "House 1 Small (Tier 1)",
        'plot': "12m x 12m",
        'description': "Single-storey square rustic log cottage with fieldstone foundation, gable roof, and stone chimney",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.7,
            'width': 7.0,
            'depth': 7.0,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.40,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_height': 2.20,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 2.8,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.42, 0.22, 0.14, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_1_SMALL_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_SMALL',
        'tier': 2,
        'name': "House 1 Small (Tier 2)",
        'plot': "12m x 12m",
        'description': "Two-storey square half-timbered town cottage with upper overhang, dormers and stone plinth",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 8.0,
            'depth': 8.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.10,
            'door_height': 2.25,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.24, 0.32, 0.44, 1.0),
            'color_wall_ext': (0.87, 0.81, 0.72, 1.0),
            'color_timber': (0.25, 0.15, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_1_SMALL_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_SMALL',
        'tier': 3,
        'name': "House 1 Small (Tier 3)",
        'plot': "12m x 12m",
        'description': "Refined two-storey square residence with stone ground floor, cantilever overhang, dormers, and handsome chimney",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.9,
            'width': 8.8,
            'depth': 8.8,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.00,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.30,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.5,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.20, 0.26, 0.36, 1.0),
            'color_wall_ext': (0.90, 0.87, 0.80, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 2 SMALL (Square Variant, Plot: 12m x 12m)
    # =========================================================================
    'HOUSE_2_SMALL_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_SMALL',
        'tier': 1,
        'name': "House 2 Small (Tier 1)",
        'plot': "12m x 12m",
        'description': "Cozy square fairytale cottage variant with pronounced sway roof, stone chimney, and warm wooden shutters",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.7,
            'width': 7.0,
            'depth': 7.0,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.40,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_height': 2.20,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.2,
            'roof_sway': 0.35,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.38, 0.22, 1.0),
            'color_wall_ext': (0.32, 0.20, 0.12, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_2_SMALL_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_SMALL',
        'tier': 2,
        'name': "House 2 Small (Tier 2)",
        'plot': "12m x 12m",
        'description': "Whimsical 2-storey sway-roof home variant with warm terracotta tones, dormers and stone base",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 8.0,
            'depth': 8.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.10,
            'door_height': 2.25,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.6,
            'roof_sway': 0.30,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.75, 0.38, 0.16, 1.0),
            'color_wall_ext': (0.88, 0.83, 0.73, 1.0),
            'color_timber': (0.28, 0.16, 0.09, 1.0),
            'window_glow_strength': 3.0
        }
    },
    'HOUSE_2_SMALL_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_SMALL',
        'tier': 3,
        'name': "House 2 Small (Tier 3)",
        'plot': "12m x 12m",
        'description': "Picturesque 2-storey fantasy villa variant with steep swayed slate roof, stone ground floor and dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.9,
            'width': 8.8,
            'depth': 8.8,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.00,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.30,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.8,
            'roof_sway': 0.28,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.20, 0.38, 0.45, 1.0),
            'color_wall_ext': (0.92, 0.89, 0.82, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 3.5
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 1 MEDIUM (Square, Plot: 20m x 20m)
    # =========================================================================
    'HOUSE_1_MEDIUM_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_MEDIUM',
        'tier': 1,
        'name': "House 1 Medium (Tier 1)",
        'plot': "20m x 20m",
        'description': "Spacious single-storey square rustic manor lodge with wide sheltering eaves, stone base, and chimney",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.9,
            'width': 12.0,
            'depth': 12.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.50,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_height': 2.40,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.6,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.36, 0.22, 0.14, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_1_MEDIUM_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_MEDIUM',
        'tier': 2,
        'name': "House 1 Medium (Tier 2)",
        'plot': "20m x 20m",
        'description': "Substantial two-storey square residence with upper cantilever overhang, multiple dormers, and timber framing",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.9,
            'width': 13.5,
            'depth': 13.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.40,
            'door_height': 2.50,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 4.0,
            'roof_sway': 0.20,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.24, 0.32, 0.44, 1.0),
            'color_wall_ext': (0.87, 0.81, 0.72, 1.0),
            'color_timber': (0.26, 0.15, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_1_MEDIUM_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_MEDIUM',
        'tier': 3,
        'name': "House 1 Medium (Tier 3)",
        'plot': "20m x 20m",
        'description': "Grand 3-storey noble square estate with ashlar stone ground storey and dual dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 3,
            'floor_height': 3.0,
            'width': 15.0,
            'depth': 15.0,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.40,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.80,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.20,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.50,
            'door_height': 2.60,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 4.5,
            'roof_overhang': 0.70,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.20, 0.24, 0.34, 1.0),
            'color_wall_ext': (0.90, 0.87, 0.80, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 2 MEDIUM (Rectangular Narrow, Plot: 12m x 20m)
    # =========================================================================
    'HOUSE_2_MEDIUM_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_MEDIUM',
        'tier': 1,
        'name': "House 2 Medium (Tier 1)",
        'plot': "12m x 20m",
        'description': "Single-storey elongated timber longhouse designed for narrow deep plots with sheltering eaves and stone base",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.8,
            'width': 7.5,
            'depth': 13.0,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.25,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.0,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.38, 0.24, 0.16, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_2_MEDIUM_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_MEDIUM',
        'tier': 2,
        'name': "House 2 Medium (Tier 2)",
        'plot': "12m x 20m",
        'description': "Two-storey narrow townhouse with elongated deep floorplan, upper overhang, rhythmic windows, and dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 8.2,
            'depth': 15.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.00,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.20,
            'door_height': 2.30,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.5,
            'roof_sway': 0.22,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.26, 0.34, 0.46, 1.0),
            'color_wall_ext': (0.86, 0.80, 0.72, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_2_MEDIUM_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_MEDIUM',
        'tier': 3,
        'name': "House 2 Medium (Tier 3)",
        'plot': "12m x 20m",
        'description': "Three-storey urban narrow guildhouse / townhouse with stone base, Tudor half-timbering, and double dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 3,
            'floor_height': 2.9,
            'width': 8.8,
            'depth': 16.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'ALL_FLOORS',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_height': 2.45,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 4.0,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.26, 0.32, 1.0),
            'color_wall_ext': (0.88, 0.85, 0.78, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 3 MEDIUM (L-Shaped, Plot: 20m x 20m with 10m cutout)
    # =========================================================================
    'HOUSE_3_MEDIUM_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_3_MEDIUM',
        'tier': 1,
        'name': "House 3 Medium (Tier 1)",
        'plot': "20m x 20m (10m cutout)",
        'description': "Single-storey L-shaped rustic homestead enclosing a private garden courtyard inside a 20m x 20m plot",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 13.0,
            'depth': 6.5,
            'wing_width': 6.0,
            'wing_depth': 6.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.25,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.40, 0.24, 0.16, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_3_MEDIUM_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_3_MEDIUM',
        'tier': 2,
        'name': "House 3 Medium (Tier 2)",
        'plot': "20m x 20m (10m cutout)",
        'description': "Two-storey L-shaped manor residence with 1-storey wing, half-timbering, stone foundation, and courtyard entry",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 14.5,
            'depth': 7.0,
            'wing_width': 6.5,
            'wing_depth': 6.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.25,
            'door_height': 2.35,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.6,
            'roof_sway': 0.24,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.24, 0.34, 0.46, 1.0),
            'color_wall_ext': (0.86, 0.80, 0.72, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_3_MEDIUM_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_3_MEDIUM',
        'tier': 3,
        'name': "House 3 Medium (Tier 3)",
        'plot': "20m x 20m (10m cutout)",
        'description': "Prestigious two-storey L-shaped estate with two full floors across both wings, ashlar masonry base, and dormers",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 16.0,
            'depth': 7.5,
            'wing_width': 7.0,
            'wing_depth': 7.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.38,
            'wonkiness': 0.0,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.15,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.35,
            'door_height': 2.50,
            'door_angle': 0.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 4.0,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.18, 0.26, 0.38, 1.0),
            'color_wall_ext': (0.88, 0.84, 0.76, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # HOSPITALITY: TAVERN (Public house / taproom, fits a 20m x 20m plot)
    # =========================================================================
    'TAVERN_T1': {
        'category': 'HOSPITALITY',
        'family': 'TAVERN',
        'tier': 1,
        'name': "Tavern (Tier 1)",
        'plot': "20m x 20m",
        'description': "Cozy half-timbered fantasy pub on a cut-stone base: arched door, terracotta sway roof with flared eaves, veranda, sign and barrels.",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.75,
            'width': 9.5,
            'depth': 8.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'cantilever_overhang': 0.38,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.70,
            'door_height': 2.45,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.3,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.5,
            'roof_sway': 0.30,
            'roof_flare': 0.42,
            'roof_overhang': 0.76,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'dormer_count': 1,
            'dormer_sides': 'FRONT_LEFT',
            'has_chimney': True,
            'chimney_pos_x': 0.65,
            'chimney_pos_y': -0.45,
            'has_hoist_beam': False,
            'has_loft_hatch': False,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_well': False,
            'color_shingles': (0.72, 0.32, 0.14, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.22, 0.12, 0.07, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'TAVERN_T2': {
        'category': 'HOSPITALITY',
        'family': 'TAVERN',
        'tier': 2,
        'name': "Tavern (Tier 2)",
        'plot': "20m x 20m",
        'description': "Two-storey half-timbered coaching tavern: stone base, corbelled upper floor, front balcony, terracotta sway roof, dormers, veranda and beer garden.",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.85,
            'width': 12.5,
            'depth': 9.8,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.48,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.15,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.70,
            'door_height': 2.50,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.2,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'has_balcony': True,
            'balcony_side': 'FRONT',
            'balcony_floor': 2,
            'balcony_width': 4.4,
            'balcony_depth': 1.40,
            'has_dormers': True,
            'dormer_count': 2,
            'dormer_sides': 'FRONT_LEFT',
            'has_chimney': True,
            'chimney_pos_x': 0.65,
            'chimney_pos_y': -0.45,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'roof_style': 'SWAY',
            'roof_height': 3.9,
            'roof_sway': 0.30,
            'roof_flare': 0.44,
            'roof_overhang': 0.80,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_side_annex': True,
            'annex_floors': 1,
            'annex_side': 'LEFT',
            'has_well': False,
            'color_shingles': (0.70, 0.28, 0.12, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.20, 0.11, 0.06, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'TAVERN_T3': {
        'category': 'HOSPITALITY',
        'family': 'TAVERN',
        'tier': 3,
        'name': "Tavern (Tier 3)",
        'plot': "20m x 20m (10m cutout)",
        'description': "Grand L-shaped fantasy courtyard tavern: stone base, twin half-timbered wings, terracotta sway roof, dormers, veranda, sign and courtyard well.",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 2.95,
            'width': 15.0,
            'depth': 9.5,
            'wing_width': 7.0,
            'wing_depth': 7.0,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.44,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.74,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.15,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.65,
            'door_height': 2.60,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.2,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'has_dormers': True,
            'dormer_count': 2,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': True,
            'wing_dormer_count': 1,
            'wing_dormer_sides': 'OUTER',
            'has_chimney': True,
            'chimney_pos_x': 0.65,
            'chimney_pos_y': -0.45,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'has_balcony': True,
            'balcony_side': 'LEFT',
            'balcony_mode': 'SINGLE',
            'balcony_floor': 2,
            'balcony_width': 3.8,
            'balcony_depth': 1.40,
            'roof_style': 'SWAY',
            'roof_height': 4.1,
            'roof_sway': 0.28,
            'roof_flare': 0.42,
            'roof_overhang': 0.78,
            'wing_roof_scale': 0.82,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_side_annex': True,
            'annex_floors': 2,
            'annex_side': 'RIGHT',
            'has_well': True,
            'color_shingles': (0.68, 0.26, 0.12, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.20, 0.11, 0.06, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },

    # =========================================================================
    # HOSPITALITY: TAVERN LONG (Narrow roadside pub, fits a 12m x 20m plot)
    # =========================================================================
    'TAVERN_LONG_T1': {
        'category': 'HOSPITALITY',
        'family': 'TAVERN_LONG',
        'tier': 1,
        'name': "Tavern Long (Tier 1)",
        'plot': "12m x 20m",
        'description': "Long roadside half-timbered tavern on a stone base: broad taproom, arched entrance, terracotta roof, veranda and hanging sign.",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.75,
            'width': 7.5,
            'depth': 14.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'cantilever_overhang': 0.35,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.00,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.70,
            'door_height': 2.45,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.3,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.5,
            'roof_sway': 0.26,
            'roof_flare': 0.40,
            'roof_overhang': 0.75,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': False,
            'has_chimney': True,
            'chimney_pos_x': 0.55,
            'chimney_pos_y': -0.55,
            'has_hoist_beam': False,
            'has_loft_hatch': False,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_well': False,
            'color_shingles': (0.70, 0.28, 0.12, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.22, 0.12, 0.07, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'TAVERN_LONG_T2': {
        'category': 'HOSPITALITY',
        'family': 'TAVERN_LONG',
        'tier': 2,
        'name': "Tavern Long (Tier 2)",
        'plot': "12m x 20m",
        'description': "Two-storey half-timbered coaching tavern on stone base: jettied upper floor, terracotta sway roof, dormers, veranda and a side beer garden.",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.85,
            'width': 8.5,
            'depth': 16.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.42,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.70,
            'door_height': 2.50,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.2,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'has_dormers': True,
            'dormer_count': 3,
            'dormer_sides': 'BOTH',
            'has_chimney': True,
            'chimney_pos_x': 0.55,
            'chimney_pos_y': -0.55,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'roof_style': 'SWAY',
            'roof_height': 3.9,
            'roof_sway': 0.28,
            'roof_flare': 0.42,
            'roof_overhang': 0.78,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_side_annex': True,
            'annex_floors': 1,
            'annex_side': 'LEFT',
            'has_well': False,
            'color_shingles': (0.70, 0.28, 0.12, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.20, 0.11, 0.06, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'TAVERN_LONG_T3': {
        'category': 'HOSPITALITY',
        'family': 'TAVERN_LONG',
        'tier': 3,
        'name': "Tavern Long (Tier 3)",
        'plot': "12m x 20m",
        'description': "Grand narrow tavern filling the plot: stone base, terracotta sway roof, dormers, long veranda, sign, balcony and a garden well down the side.",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.95,
            'width': 9.8,
            'depth': 18.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.45,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.74,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.15,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.60,
            'door_height': 2.55,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.1,
            'has_shutters': True,
            'shutter_state': 'PARTIAL',
            'shutter_closed_amount': 0.25,
            'has_timber_framing': True,
            'timber_diagonals': True,
            'has_dormers': True,
            'dormer_count': 4,
            'dormer_sides': 'BOTH',
            'has_chimney': True,
            'chimney_pos_x': 0.55,
            'chimney_pos_y': -0.55,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'has_balcony': True,
            'balcony_side': 'RIGHT',
            'balcony_mode': 'SINGLE',
            'balcony_floor': 2,
            'balcony_width': 3.6,
            'balcony_depth': 1.35,
            'roof_style': 'SWAY',
            'roof_height': 4.4,
            'roof_sway': 0.26,
            'roof_flare': 0.42,
            'roof_overhang': 0.78,
            'has_roof_shingles': True,
            'shingle_rows': 10,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_side_annex': True,
            'annex_floors': 2,
            'annex_side': 'LEFT',
            'has_well': True,
            'color_shingles': (0.68, 0.26, 0.12, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.20, 0.11, 0.06, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },

    # =========================================================================
    # HOSPITALITY: INN (Accommodation + pub, fits a 40m x 40m plot)
    # =========================================================================
    'INN_T1': {
        'category': 'HOSPITALITY',
        'family': 'INN',
        'tier': 1,
        'name': "Inn (Tier 1)",
        'plot': "40m x 40m",
        'description': "Two-storey wayside half-timbered inn with guest wing: cut-stone base, terracotta sway roof, dormers, veranda, sign, hay yard and courtyard well.",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 2.85,
            'width': 14.0,
            'depth': 9.0,
            'wing_width': 6.5,
            'wing_depth': 6.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'cantilever_overhang': 0.38,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.70,
            'door_height': 2.45,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.2,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'has_dormers': True,
            'dormer_count': 2,
            'dormer_sides': 'FRONT_LEFT',
            'has_wing_dormers': True,
            'wing_dormer_count': 1,
            'wing_dormer_sides': 'OUTER',
            'has_chimney': True,
            'chimney_pos_x': 0.65,
            'chimney_pos_y': -0.45,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'roof_style': 'SWAY',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.9,
            'roof_sway': 0.28,
            'roof_flare': 0.42,
            'roof_overhang': 0.76,
            'wing_roof_scale': 0.82,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_side_annex': True,
            'annex_floors': 1,
            'annex_side': 'LEFT',
            'has_well': True,
            'color_shingles': (0.72, 0.30, 0.14, 1.0),
            'color_wall_ext': (0.91, 0.87, 0.79, 1.0),
            'color_timber': (0.20, 0.11, 0.06, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'INN_T2': {
        'category': 'HOSPITALITY',
        'family': 'INN',
        'tier': 2,
        'name': "Inn (Tier 2)",
        'plot': "40m x 40m",
        'description': "Large three-storey half-timbered coaching inn: dramatic cantilevers, full front balcony, bay windows, terracotta sway roof, dormers, veranda and courtyard.",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 3,
            'wing_floors': 2,
            'floor_height': 2.9,
            'width': 18.0,
            'depth': 11.0,
            'wing_width': 8.0,
            'wing_depth': 7.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.52,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.20,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.75,
            'door_height': 2.60,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.1,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'has_balcony': True,
            'balcony_side': 'FRONT',
            'balcony_mode': 'SINGLE',
            'balcony_floor': 2,
            'balcony_width': 5.0,
            'balcony_depth': 1.50,
            'has_mini_wing': True,
            'mini_wing_count': 2,
            'mini_wing_width': 2.4,
            'mini_wing_depth': 1.6,
            'mini_wing_roof': 'GABLE',
            'has_dormers': True,
            'dormer_count': 3,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': True,
            'wing_dormer_count': 2,
            'wing_dormer_sides': 'OUTER',
            'has_chimney': True,
            'chimney_pos_x': 0.65,
            'chimney_pos_y': -0.45,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'roof_style': 'SWAY',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 4.4,
            'roof_sway': 0.30,
            'roof_flare': 0.45,
            'roof_overhang': 0.82,
            'wing_roof_scale': 0.82,
            'has_roof_shingles': True,
            'shingle_rows': 10,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_side_annex': True,
            'annex_floors': 2,
            'annex_side': 'LEFT',
            'has_well': True,
            'color_shingles': (0.70, 0.28, 0.12, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.20, 0.11, 0.06, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },
    'INN_T3': {
        'category': 'HOSPITALITY',
        'family': 'INN',
        'tier': 3,
        'name': "Inn (Tier 3)",
        'plot': "40m x 40m (24m cutout)",
        'description': "Grand whimsical fantasy inn filling the plot: four storeys across an L, stone base, stacked cantilevers, balconies, bay windows, terracotta sway roof, well and courtyard.",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 4,
            'wing_floors': 2,
            'floor_height': 2.95,
            'width': 20.0,
            'depth': 12.0,
            'wing_width': 8.5,
            'wing_depth': 8.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.55,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.85,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.25,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.85,
            'door_height': 2.70,
            'door_angle': 0.0,
            'door_shape': 'ARCHED',
            'has_windows': True,
            'window_spacing': 2.0,
            'has_shutters': True,
            'shutter_state': 'OPEN',
            'has_timber_framing': True,
            'timber_diagonals': True,
            'has_balcony': True,
            'balcony_side': 'FRONT',
            'balcony_mode': 'SINGLE',
            'balcony_floor': 2,
            'balcony_width': 5.5,
            'balcony_depth': 1.55,
            'has_mini_wing': True,
            'mini_wing_count': 3,
            'mini_wing_width': 2.5,
            'mini_wing_depth': 1.7,
            'mini_wing_roof': 'GABLE',
            'has_dormers': True,
            'dormer_count': 4,
            'dormer_sides': 'BOTH',
            'has_wing_dormers': True,
            'wing_dormer_count': 2,
            'wing_dormer_sides': 'OUTER',
            'has_chimney': True,
            'chimney_pos_x': 0.65,
            'chimney_pos_y': -0.45,
            'has_hoist_beam': False,
            'has_loft_hatch': True,
            'roof_style': 'SWAY',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 4.8,
            'roof_sway': 0.28,
            'roof_flare': 0.45,
            'roof_overhang': 0.85,
            'wing_roof_scale': 0.82,
            'has_roof_shingles': True,
            'shingle_rows': 11,
            'has_veranda': True,
            'has_trade_sign': True,
            'has_flower_boxes': True,
            'has_outdoor_decor': True,
            'has_side_annex': True,
            'annex_floors': 2,
            'annex_side': 'LEFT',
            'has_well': True,
            'color_shingles': (0.68, 0.26, 0.12, 1.0),
            'color_wall_ext': (0.92, 0.88, 0.80, 1.0),
            'color_timber': (0.20, 0.11, 0.06, 1.0),
            'color_stone': (0.44, 0.42, 0.39, 1.0),
            'window_glow_strength': 3.5
        }
    },
}

BUILDING_FAMILIES = [
    {
        'id': 'TOWN_HALL',
        'name': "Town Hall",
        'category': 'CIVIC',
        'plot': "40m x 40m",
        'shape': "T-Shaped",
        'icon': 'COMMUNITY',
        'tiers': [
            ('T1', 'TOWN_HALL_T1', "Tier 1: Log Hall + Porch + Balcony"),
            ('T2', 'TOWN_HALL_T2', "Tier 2: Belfry Hall + Oriel + Balconies"),
            ('T3', 'TOWN_HALL_T3', "Tier 3: Clock-Tower Hall + Annex + Colonnade"),
        ]
    },
    {
        'id': 'WAREHOUSE',
        'name': "Warehouse",
        'category': 'INDUSTRIAL',
        'plot': "20m x 20m",
        'shape': "L-Shaped",
        'icon': 'MOD_BUILD',
        'tiers': [
            ('T1', 'WAREHOUSE_T1', "Tier 1: Open Timber Post & Roof"),
            ('T2', 'WAREHOUSE_T2', "Tier 2: Walled Depot + Crane"),
            ('T3', 'WAREHOUSE_T3', "Tier 3: Large Storehouse + Crane"),
        ]
    },
    {
        'id': 'LUMBERMILL',
        'name': "Lumbermill",
        'category': 'INDUSTRIAL',
        'plot': "20m x 20m",
        'shape': "Rectangular",
        'icon': 'OUTLINER_OB_MESH',
        'tiers': [
            ('T1', 'LUMBERMILL_T1', "Tier 1: Treadwheel + Saw Bench"),
            ('T2', 'LUMBERMILL_T2', "Tier 2: Geared Drive + Carriage"),
            ('T3', 'LUMBERMILL_T3', "Tier 3: Line-Shaft Mill Hall"),
        ]
    },
    {
        'id': 'INFANTRY_BARRACKS',
        'name': "Infantry Barracks",
        'category': 'MILITARY',
        'plot': "40m x 40m",
        'shape': "U-Shaped",
        'icon': 'GROUP',
        'tiers': [
            ('T1', 'INFANTRY_BARRACKS_T1', "Tier 1: Log Camp + Stone Gate Porch"),
            ('T2', 'INFANTRY_BARRACKS_T2', "Tier 2: Plank HQ + Oriels + Loft Hatch"),
            ('T3', 'INFANTRY_BARRACKS_T3', "Tier 3: Citadel + Clock Tower & Spires"),
        ]
    },
    {
        'id': 'HOUSE_1_SMALL',
        'name': "House 1 Small",
        'category': 'RESIDENTIAL',
        'plot': "12m x 12m",
        'shape': "Square",
        'icon': 'HOME',
        'tiers': [
            ('T1', 'HOUSE_1_SMALL_T1', "Tier 1: Rustic Square Cottage"),
            ('T2', 'HOUSE_1_SMALL_T2', "Tier 2: Half-Timbered Town Cottage"),
            ('T3', 'HOUSE_1_SMALL_T3', "Tier 3: Stone Plinth Residence"),
        ]
    },
    {
        'id': 'HOUSE_2_SMALL',
        'name': "House 2 Small",
        'category': 'RESIDENTIAL',
        'plot': "12m x 12m",
        'shape': "Square (Fairytale)",
        'icon': 'LIGHT_SUN',
        'tiers': [
            ('T1', 'HOUSE_2_SMALL_T1', "Tier 1: Sway-Roof Forest Cottage"),
            ('T2', 'HOUSE_2_SMALL_T2', "Tier 2: Terracotta Sway Home"),
            ('T3', 'HOUSE_2_SMALL_T3', "Tier 3: Fantasy Slate Villa"),
        ]
    },
    {
        'id': 'HOUSE_1_MEDIUM',
        'name': "House 1 Medium",
        'category': 'RESIDENTIAL',
        'plot': "20m x 20m",
        'shape': "Square",
        'icon': 'HOME',
        'tiers': [
            ('T1', 'HOUSE_1_MEDIUM_T1', "Tier 1: Rustic Manor Lodge"),
            ('T2', 'HOUSE_1_MEDIUM_T2', "Tier 2: 2-Storey Manor Home"),
            ('T3', 'HOUSE_1_MEDIUM_T3', "Tier 3: 3-Storey Noble Estate"),
        ]
    },
    {
        'id': 'HOUSE_2_MEDIUM',
        'name': "House 2 Medium",
        'category': 'RESIDENTIAL',
        'plot': "12m x 20m",
        'shape': "Rectangular Narrow",
        'icon': 'FILE_TEXT',
        'tiers': [
            ('T1', 'HOUSE_2_MEDIUM_T1', "Tier 1: Timber Longhouse"),
            ('T2', 'HOUSE_2_MEDIUM_T2', "Tier 2: 2-Storey Narrow Townhouse"),
            ('T3', 'HOUSE_2_MEDIUM_T3', "Tier 3: 3-Storey Guildhouse"),
        ]
    },
    {
        'id': 'HOUSE_3_MEDIUM',
        'name': "House 3 Medium",
        'category': 'RESIDENTIAL',
        'plot': "20m x 20m (10m cutout)",
        'shape': "L-Shaped",
        'icon': 'SNAP_VOLUME',
        'tiers': [
            ('T1', 'HOUSE_3_MEDIUM_T1', "Tier 1: Courtyard Homestead"),
            ('T2', 'HOUSE_3_MEDIUM_T2', "Tier 2: L-Manor Residence"),
            ('T3', 'HOUSE_3_MEDIUM_T3', "Tier 3: Grand L-Estate"),
        ]
    },
    {
        'id': 'TAVERN',
        'name': "Tavern",
        'category': 'HOSPITALITY',
        'plot': "20m x 20m",
        'shape': "Pub",
        'icon': 'SORT_DESC',
        'tiers': [
            ('T1', 'TAVERN_T1', "Tier 1: Log Taproom + Veranda & Sign"),
            ('T2', 'TAVERN_T2', "Tier 2: Half-Timbered Pub + Beer Garden"),
            ('T3', 'TAVERN_T3', "Tier 3: L-Tavern + Well & Balcony"),
        ]
    },
    {
        'id': 'TAVERN_LONG',
        'name': "Tavern Long",
        'category': 'HOSPITALITY',
        'plot': "12m x 20m",
        'shape': "Long Pub",
        'icon': 'ALIGN_JUSTIFY',
        'tiers': [
            ('T1', 'TAVERN_LONG_T1', "Tier 1: Long Log Roadhouse"),
            ('T2', 'TAVERN_LONG_T2', "Tier 2: Coaching Tavern + Side Garden"),
            ('T3', 'TAVERN_LONG_T3', "Tier 3: Grand Long Tavern + Well"),
        ]
    },
    {
        'id': 'INN',
        'name': "Inn",
        'category': 'HOSPITALITY',
        'plot': "40m x 40m",
        'shape': "Coaching Inn",
        'icon': 'HOME',
        'tiers': [
            ('T1', 'INN_T1', "Tier 1: Wayside Log Inn + Dormers"),
            ('T2', 'INN_T2', "Tier 2: 3-Storey Coaching Inn + Balconies"),
            ('T3', 'INN_T3', "Tier 3: Grand Country Inn + Spire & Well"),
        ]
    },
]

ARCHETYPE_MAP = {
    'WAREHOUSE_T1': 'WAREHOUSE',
    'WAREHOUSE_T2': 'WAREHOUSE',
    'WAREHOUSE_T3': 'WAREHOUSE',
    'LUMBERMILL_T1': 'LUMBERMILL',
    'LUMBERMILL_T2': 'LUMBERMILL',
    'LUMBERMILL_T3': 'LUMBERMILL',
    'TAVERN_T1': 'TAVERN',
    'TAVERN_T2': 'TAVERN',
    'TAVERN_T3': 'TAVERN',
    'TAVERN_LONG_T1': 'TAVERN',
    'TAVERN_LONG_T2': 'TAVERN',
    'TAVERN_LONG_T3': 'TAVERN',
    'INN_T1': 'INN',
    'INN_T2': 'INN',
    'INN_T3': 'INN',
}

def apply_preset(props, preset_key):
    """Applies preset dictionary values to the PropertyGroup."""
    if preset_key not in PRESETS:
        return
        
    data = PRESETS[preset_key]['settings']
    # Temporarily disable auto_update during batch assignment to avoid multiple regenerations
    old_auto = props.auto_update
    props.auto_update = False

    # Fortification props are optional; clear them first so a preset that omits
    # them does not inherit the previous building's palisade/banners/battlements.
    for _fk in ('has_palisade', 'palisade_style', 'palisade_height', 'palisade_offset',
                'has_curtain_wall', 'curtain_wall_height', 'curtain_wall_thickness',
                'curtain_wall_offset', 'curtain_wall_depth_extra',
                'has_banners', 'banner_count', 'has_battlements', 'battlement_style',
                'has_military_props', 'military_props_count',
                'has_mounted_shields', 'shield_placement',
                'has_gable_crest', 'gable_crest_style', 'gable_crest_scale',
                'has_bastion_towers', 'bastion_tower_count', 'bastion_tower_size', 'bastion_tower_height',
                'has_veranda', 'has_trade_sign', 'has_flower_boxes',
                'has_outdoor_decor', 'has_well',
                'has_side_annex', 'annex_floors', 'annex_side'):
        if hasattr(props, _fk):
            try:
                props.property_unset(_fk)
            except Exception:
                pass

    # Assign archetype
    arch = ARCHETYPE_MAP.get(preset_key, 'NONE')
    if hasattr(props, 'building_archetype'):
        props.building_archetype = arch
        
    for k, v in data.items():
        if hasattr(props, k):
            setattr(props, k, v)
            
    props.auto_update = old_auto
    
    # Trigger final regeneration
    if old_auto:
        from .generator.building import generate_building
        import bpy
        context = bpy.context
        obj = context.active_object
        if obj and obj.get("is_fantasy_building", False):
            generate_building(obj, props)
