"""
Purpose-built architectural style presets for Stylized Fantasy Buildings.
Strictly calibrated to plot sizes (12m x 12m, 20m x 20m, 12m x 20m, and 40m x 40m).

Catalog:
- Town Hall (T-shaped, T1-T3) [Plot: 40m x 40m]
- Warehouse (L-shaped, T1-T3) [Plot: 20m x 20m, courtyard crane, no hook]
- Lumbermill (L-shaped, T1-T3) [Plot: 20m x 20m, all open timber frame, expanding T1-T3]
- Infantry Barracks (U-shaped, T1-T3) [Plot: 40m x 40m]
- House 1 Small (Square, T1-T3) [Plot: 12m x 12m]
- House 2 Small (Square variant, T1-T3) [Plot: 12m x 12m]
- House 1 Medium (Square, T1-T3) [Plot: 20m x 20m]
- House 2 Medium (Rectangular narrow, T1-T3) [Plot: 12m x 20m]
- House 3 Medium (L-shaped, T1-T3) [Plot: 20m x 20m with 10m x 10m cutout]
"""

PRESET_CATEGORIES = [
    ('ALL', "All Presets", "Show all building style presets"),
    ('CIVIC', "Civic", "Town halls and civic estates"),
    ('MILITARY', "Military", "Barracks and military quarters"),
    ('INDUSTRIAL', "Industrial", "Warehouses, storage, and lumbermills"),
    ('RESIDENTIAL', "Residential", "Houses, cottages, and town residences"),
]

PRESETS = {
    # =========================================================================
    # CIVIC: TOWN HALL (T-Shaped, Plot: 40m x 40m)
    # =========================================================================
    'TOWN_HALL_T1': {
        'category': 'CIVIC',
        'family': 'TOWN_HALL',
        'tier': 1,
        'name': "Town Hall (Tier 1)",
        'plot': "40m x 40m",
        'description': "Two-storey rustic timber-framed civic lodge with central T-wing projection, stone foundation, and high roof",
        'settings': {
            'building_shape': 'T_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 3.0,
            'width': 16.0,
            'depth': 10.0,
            'wing_width': 7.5,
            'wing_depth': 6.5,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.50,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.50,
            'door_height': 2.40,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.8,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.45, 0.22, 0.14, 1.0),
            'color_wall_ext': (0.86, 0.82, 0.74, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'TOWN_HALL_T2': {
        'category': 'CIVIC',
        'family': 'TOWN_HALL',
        'tier': 2,
        'name': "Town Hall (Tier 2)",
        'plot': "40m x 40m",
        'description': "Substantial two-storey civic hall with full 2-floor T-wing, cantilever overhangs, dormers, and stone masonry base",
        'settings': {
            'building_shape': 'T_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 24.0,
            'depth': 12.0,
            'wing_width': 10.0,
            'wing_depth': 8.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.20,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.80,
            'door_height': 2.60,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 4.5,
            'roof_sway': 0.20,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.20, 0.28, 0.44, 1.0),
            'color_wall_ext': (0.88, 0.84, 0.76, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'TOWN_HALL_T3': {
        'category': 'CIVIC',
        'family': 'TOWN_HALL',
        'tier': 3,
        'name': "Town Hall (Tier 3)",
        'plot': "40m x 40m",
        'description': "Grand 3-storey municipal town hall with massive T-cross wing, ashlar stone ground floor and dormers",
        'settings': {
            'building_shape': 'T_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 3,
            'wing_floors': 2,
            'floor_height': 3.2,
            'width': 32.0,
            'depth': 14.0,
            'wing_width': 12.5,
            'wing_depth': 11.0,
            'wall_thickness': 0.32,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.40,
            'wonkiness': 0.03,
            'has_foundation': True,
            'foundation_height': 0.90,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.30,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.00,
            'door_height': 2.80,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 5.2,
            'roof_overhang': 0.70,
            'has_roof_shingles': True,
            'shingle_rows': 10,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.18, 0.24, 0.38, 1.0),
            'color_wall_ext': (0.90, 0.88, 0.82, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # INDUSTRIAL: WAREHOUSE (L-Shaped, Plot: 20m x 20m, Courtyard Crane, No Hook)
    # =========================================================================
    'WAREHOUSE_T1': {
        'category': 'INDUSTRIAL',
        'family': 'WAREHOUSE',
        'tier': 1,
        'name': "Warehouse (Tier 1)",
        'plot': "20m x 20m",
        'description': "L-shaped open timber storage depot with heavy pillars and roof only (NO walls), equipped with courtyard swivel crane",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': True,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 3.2,
            'width': 12.0,
            'depth': 6.5,
            'wing_width': 5.5,
            'wing_depth': 5.5,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.40,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.2,
            'roof_overhang': 0.55,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.34, 0.22, 0.15, 1.0),
            'color_wall_ext': (0.35, 0.24, 0.15, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'WAREHOUSE_T2': {
        'category': 'INDUSTRIAL',
        'family': 'WAREHOUSE',
        'tier': 2,
        'name': "Warehouse (Tier 2)",
        'plot': "20m x 20m",
        'description': "Enclosed two-storey L-shaped cargo warehouse with solid walls, wide freight portals, dormers, and courtyard swivel crane",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 3.0,
            'width': 13.5,
            'depth': 7.0,
            'wing_width': 6.2,
            'wing_depth': 6.2,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.20,
            'door_height': 2.50,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.6,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.28, 0.32, 0.38, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.25, 0.15, 0.09, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'WAREHOUSE_T3': {
        'category': 'INDUSTRIAL',
        'family': 'WAREHOUSE',
        'tier': 3,
        'name': "Warehouse (Tier 3)",
        'plot': "20m x 20m",
        'description': "Expansive two-storey L-shaped trade depot with dual full-height wings, stone base, upper overhang, and heavy courtyard crane",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 3.2,
            'width': 15.5,
            'depth': 7.8,
            'wing_width': 7.0,
            'wing_depth': 7.2,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.03,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.15,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.40,
            'door_height': 2.70,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 4.0,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.24, 0.28, 1.0),
            'color_wall_ext': (0.88, 0.84, 0.76, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 2.0
        }
    },

    # =========================================================================
    # INDUSTRIAL: LUMBERMILL (L-Shaped, Plot: 20m x 20m, All Open Pillars/Roof)
    # =========================================================================
    'LUMBERMILL_T1': {
        'category': 'INDUSTRIAL',
        'family': 'LUMBERMILL',
        'tier': 1,
        'name': "Lumbermill (Tier 1)",
        'plot': "20m x 20m",
        'description': "Open timber sawmill pavilion matching Warehouse T1 proportions, with log skidway and timber sawbucks, NO walls",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': True,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 3.2,
            'width': 12.0,
            'depth': 6.5,
            'wing_width': 5.5,
            'wing_depth': 5.5,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.35,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.2,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.34, 0.22, 0.15, 1.0),
            'color_wall_ext': (0.35, 0.24, 0.15, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'LUMBERMILL_T2': {
        'category': 'INDUSTRIAL',
        'family': 'LUMBERMILL',
        'tier': 2,
        'name': "Lumbermill (Tier 2)",
        'plot': "20m x 20m",
        'description': "Enlarged open timber sawmill pavilion with heavy post-and-beam arcade, log skidway, and lumber stacks, NO walls",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': True,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 3.4,
            'width': 13.5,
            'depth': 7.0,
            'wing_width': 6.2,
            'wing_depth': 6.2,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.5,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.38, 0.26, 0.18, 1.0),
            'color_wall_ext': (0.35, 0.24, 0.15, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 1.0
        }
    },
    'LUMBERMILL_T3': {
        'category': 'INDUSTRIAL',
        'family': 'LUMBERMILL',
        'tier': 3,
        'name': "Lumbermill (Tier 3)",
        'plot': "20m x 20m",
        'description': "Full-capacity industrial timber milling shelter with massive timber bays, log skidway, and lumber storage, NO walls",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': True,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 3.6,
            'width': 15.5,
            'depth': 7.8,
            'wing_width': 7.0,
            'wing_depth': 7.2,
            'wall_thickness': 0.30,
            'has_cantilever': False,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': False,
            'has_windows': False,
            'has_timber_framing': True,
            'timber_diagonals': False,
            'roof_style': 'GABLE',
            'roof_orientation': 'LEFT_RIGHT',
            'roof_height': 3.8,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': False,
            'has_chimney': False,
            'has_hoist_beam': False,
            'color_shingles': (0.42, 0.28, 0.20, 1.0),
            'color_wall_ext': (0.35, 0.24, 0.15, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 1.0
        }
    },

    # =========================================================================
    # MILITARY: INFANTRY BARRACKS (U-Shaped, Plot: 40m x 40m)
    # =========================================================================
    'INFANTRY_BARRACKS_T1': {
        'category': 'MILITARY',
        'family': 'INFANTRY_BARRACKS',
        'tier': 1,
        'name': "Infantry Barracks (Tier 1)",
        'plot': "40m x 40m",
        'description': "Single-storey U-shaped timber garrison camp with twin dorm wings enclosing a central drill/muster courtyard",
        'settings': {
            'building_shape': 'U_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 20.0,
            'depth': 7.5,
            'wing_depth': 7.0,
            'courtyard_width': 7.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.50,
            'door_height': 2.30,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'roof_overhang': 0.55,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.28, 0.32, 0.36, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 1.5
        }
    },
    'INFANTRY_BARRACKS_T2': {
        'category': 'MILITARY',
        'family': 'INFANTRY_BARRACKS',
        'tier': 2,
        'name': "Infantry Barracks (Tier 2)",
        'plot': "40m x 40m",
        'description': "Two-storey U-shaped garrison headquarters with central training courtyard, stone base, dormers, and command quarters",
        'settings': {
            'building_shape': 'U_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 27.0,
            'depth': 9.5,
            'wing_depth': 9.0,
            'courtyard_width': 9.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.03,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.80,
            'door_height': 2.50,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.6,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.26, 0.28, 0.32, 1.0),
            'color_wall_ext': (0.84, 0.78, 0.68, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'INFANTRY_BARRACKS_T3': {
        'category': 'MILITARY',
        'family': 'INFANTRY_BARRACKS',
        'tier': 3,
        'name': "Infantry Barracks (Tier 3)",
        'plot': "40m x 40m",
        'description': "Massive fortified two-storey military garrison with dual multi-tier wings, stone masonry base, and high capacity quarters",
        'settings': {
            'building_shape': 'U_SHAPE',
            'wing_placement': 'FRONT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 33.0,
            'depth': 11.5,
            'wing_depth': 11.5,
            'courtyard_width': 11.0,
            'wall_thickness': 0.32,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.03,
            'has_foundation': True,
            'foundation_height': 0.85,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.20,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 2.00,
            'door_height': 2.60,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 4.2,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.24, 0.26, 1.0),
            'color_wall_ext': (0.86, 0.82, 0.74, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 2.5
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 1 SMALL (Square, Plot: 12m x 12m)
    # =========================================================================
    'HOUSE_1_SMALL_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_SMALL',
        'tier': 1,
        'name': "House 1 Small (Tier 1)",
        'plot': "12m x 12m",
        'description': "Single-storey square rustic log cottage with fieldstone foundation, gable roof, and stone chimney",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.7,
            'width': 7.0,
            'depth': 7.0,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.08,
            'has_foundation': True,
            'foundation_height': 0.40,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_height': 2.20,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 2.8,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.42, 0.22, 0.14, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_1_SMALL_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_SMALL',
        'tier': 2,
        'name': "House 1 Small (Tier 2)",
        'plot': "12m x 12m",
        'description': "Two-storey square half-timbered town cottage with upper overhang, dormers and stone plinth",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 8.0,
            'depth': 8.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.30,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.10,
            'door_height': 2.25,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.24, 0.32, 0.44, 1.0),
            'color_wall_ext': (0.87, 0.81, 0.72, 1.0),
            'color_timber': (0.25, 0.15, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_1_SMALL_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_SMALL',
        'tier': 3,
        'name': "House 1 Small (Tier 3)",
        'plot': "12m x 12m",
        'description': "Refined two-storey square residence with stone ground floor, cantilever overhang, dormers, and handsome chimney",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.9,
            'width': 8.8,
            'depth': 8.8,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.00,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.30,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.5,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.20, 0.26, 0.36, 1.0),
            'color_wall_ext': (0.90, 0.87, 0.80, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 2 SMALL (Square Variant, Plot: 12m x 12m)
    # =========================================================================
    'HOUSE_2_SMALL_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_SMALL',
        'tier': 1,
        'name': "House 2 Small (Tier 1)",
        'plot': "12m x 12m",
        'description': "Cozy square fairytale cottage variant with pronounced sway roof, stone chimney, and warm wooden shutters",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.7,
            'width': 7.0,
            'depth': 7.0,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.10,
            'has_foundation': True,
            'foundation_height': 0.40,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.05,
            'door_height': 2.20,
            'door_angle': 35.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.2,
            'roof_sway': 0.35,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 6,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.38, 0.22, 1.0),
            'color_wall_ext': (0.32, 0.20, 0.12, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_2_SMALL_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_SMALL',
        'tier': 2,
        'name': "House 2 Small (Tier 2)",
        'plot': "12m x 12m",
        'description': "Whimsical 2-storey sway-roof home variant with warm terracotta tones, dormers and stone base",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 8.0,
            'depth': 8.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.08,
            'has_foundation': True,
            'foundation_height': 0.55,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 0.95,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.10,
            'door_height': 2.25,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.6,
            'roof_sway': 0.30,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.75, 0.38, 0.16, 1.0),
            'color_wall_ext': (0.88, 0.83, 0.73, 1.0),
            'color_timber': (0.28, 0.16, 0.09, 1.0),
            'window_glow_strength': 3.0
        }
    },
    'HOUSE_2_SMALL_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_SMALL',
        'tier': 3,
        'name': "House 2 Small (Tier 3)",
        'plot': "12m x 12m",
        'description': "Picturesque 2-storey fantasy villa variant with steep swayed slate roof, stone ground floor and dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.9,
            'width': 8.8,
            'depth': 8.8,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.70,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.00,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.30,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.8,
            'roof_sway': 0.28,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.20, 0.38, 0.45, 1.0),
            'color_wall_ext': (0.92, 0.89, 0.82, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 3.5
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 1 MEDIUM (Square, Plot: 20m x 20m)
    # =========================================================================
    'HOUSE_1_MEDIUM_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_MEDIUM',
        'tier': 1,
        'name': "House 1 Medium (Tier 1)",
        'plot': "20m x 20m",
        'description': "Spacious single-storey square rustic manor lodge with wide sheltering eaves, stone base, and chimney",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.9,
            'width': 12.0,
            'depth': 12.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.50,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_height': 2.40,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.6,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.36, 0.22, 0.14, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_1_MEDIUM_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_MEDIUM',
        'tier': 2,
        'name': "House 1 Medium (Tier 2)",
        'plot': "20m x 20m",
        'description': "Substantial two-storey square residence with upper cantilever overhang, multiple dormers, and timber framing",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.9,
            'width': 13.5,
            'depth': 13.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.65,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.10,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.40,
            'door_height': 2.50,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 4.0,
            'roof_sway': 0.20,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.24, 0.32, 0.44, 1.0),
            'color_wall_ext': (0.87, 0.81, 0.72, 1.0),
            'color_timber': (0.26, 0.15, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_1_MEDIUM_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_1_MEDIUM',
        'tier': 3,
        'name': "House 1 Medium (Tier 3)",
        'plot': "20m x 20m",
        'description': "Grand 3-storey noble square estate with ashlar stone ground storey and dual dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 3,
            'floor_height': 3.0,
            'width': 15.0,
            'depth': 15.0,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.40,
            'wonkiness': 0.03,
            'has_foundation': True,
            'foundation_height': 0.80,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.20,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.50,
            'door_height': 2.60,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 4.5,
            'roof_overhang': 0.70,
            'has_roof_shingles': True,
            'shingle_rows': 9,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.20, 0.24, 0.34, 1.0),
            'color_wall_ext': (0.90, 0.87, 0.80, 1.0),
            'color_timber': (0.20, 0.12, 0.07, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 2 MEDIUM (Rectangular Narrow, Plot: 12m x 20m)
    # =========================================================================
    'HOUSE_2_MEDIUM_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_MEDIUM',
        'tier': 1,
        'name': "House 2 Medium (Tier 1)",
        'plot': "12m x 20m",
        'description': "Single-storey elongated timber longhouse designed for narrow deep plots with sheltering eaves and stone base",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'floor_height': 2.8,
            'width': 7.5,
            'depth': 13.0,
            'wall_thickness': 0.26,
            'has_cantilever': False,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.25,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.0,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.38, 0.24, 0.16, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_2_MEDIUM_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_MEDIUM',
        'tier': 2,
        'name': "House 2 Medium (Tier 2)",
        'plot': "12m x 20m",
        'description': "Two-storey narrow townhouse with elongated deep floorplan, upper overhang, rhythmic windows, and dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'floor_height': 2.8,
            'width': 8.2,
            'depth': 15.0,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.00,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.20,
            'door_height': 2.30,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.5,
            'roof_sway': 0.22,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.26, 0.34, 0.46, 1.0),
            'color_wall_ext': (0.86, 0.80, 0.72, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_2_MEDIUM_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_2_MEDIUM',
        'tier': 3,
        'name': "House 2 Medium (Tier 3)",
        'plot': "12m x 20m",
        'description': "Three-storey urban narrow guildhouse / townhouse with stone base, Tudor half-timbering, and double dormers",
        'settings': {
            'building_shape': 'RECTANGLE',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 3,
            'floor_height': 2.9,
            'width': 8.8,
            'depth': 16.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'ALL_FLOORS',
            'cantilever_overhang': 0.32,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.30,
            'door_height': 2.45,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 4.0,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.22, 0.26, 0.32, 1.0),
            'color_wall_ext': (0.88, 0.85, 0.78, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 3.0
        }
    },

    # =========================================================================
    # RESIDENTIAL: HOUSE 3 MEDIUM (L-Shaped, Plot: 20m x 20m with 10m cutout)
    # =========================================================================
    'HOUSE_3_MEDIUM_T1': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_3_MEDIUM',
        'tier': 1,
        'name': "House 3 Medium (Tier 1)",
        'plot': "20m x 20m (10m cutout)",
        'description': "Single-storey L-shaped rustic homestead enclosing a private garden courtyard inside a 20m x 20m plot",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_1',
            'open_timber_frame': False,
            'num_floors': 1,
            'wing_floors': 1,
            'floor_height': 2.8,
            'width': 13.0,
            'depth': 6.5,
            'wing_width': 6.0,
            'wing_depth': 6.0,
            'wall_thickness': 0.28,
            'has_cantilever': False,
            'wonkiness': 0.06,
            'has_foundation': True,
            'foundation_height': 0.45,
            'ground_floor_stone': False,
            'has_front_steps': True,
            'has_stairs': False,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.15,
            'door_height': 2.25,
            'door_angle': 30.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 3.2,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 7,
            'has_dormers': False,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.40, 0.24, 0.16, 1.0),
            'color_wall_ext': (0.34, 0.22, 0.14, 1.0),
            'color_timber': (0.24, 0.14, 0.08, 1.0),
            'window_glow_strength': 2.0
        }
    },
    'HOUSE_3_MEDIUM_T2': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_3_MEDIUM',
        'tier': 2,
        'name': "House 3 Medium (Tier 2)",
        'plot': "20m x 20m (10m cutout)",
        'description': "Two-storey L-shaped manor residence with 1-storey wing, half-timbering, stone foundation, and courtyard entry",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_2',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 1,
            'floor_height': 2.9,
            'width': 14.5,
            'depth': 7.0,
            'wing_width': 6.5,
            'wing_depth': 6.5,
            'wall_thickness': 0.28,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.35,
            'wonkiness': 0.05,
            'has_foundation': True,
            'foundation_height': 0.60,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.05,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.25,
            'door_height': 2.35,
            'door_angle': 25.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'SWAY',
            'roof_height': 3.6,
            'roof_sway': 0.24,
            'roof_overhang': 0.60,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.24, 0.34, 0.46, 1.0),
            'color_wall_ext': (0.86, 0.80, 0.72, 1.0),
            'color_timber': (0.26, 0.16, 0.09, 1.0),
            'window_glow_strength': 2.5
        }
    },
    'HOUSE_3_MEDIUM_T3': {
        'category': 'RESIDENTIAL',
        'family': 'HOUSE_3_MEDIUM',
        'tier': 3,
        'name': "House 3 Medium (Tier 3)",
        'plot': "20m x 20m (10m cutout)",
        'description': "Prestigious two-storey L-shaped estate with two full floors across both wings, ashlar masonry base, and dormers",
        'settings': {
            'building_shape': 'L_SHAPE',
            'wing_placement': 'FRONT',
            'wing_side': 'RIGHT',
            'material_tier': 'TIER_3',
            'open_timber_frame': False,
            'num_floors': 2,
            'wing_floors': 2,
            'floor_height': 3.0,
            'width': 16.0,
            'depth': 7.5,
            'wing_width': 7.0,
            'wing_depth': 7.5,
            'wall_thickness': 0.30,
            'has_cantilever': True,
            'overhang_mode': 'SECOND_FLOOR_ONLY',
            'cantilever_overhang': 0.38,
            'wonkiness': 0.04,
            'has_foundation': True,
            'foundation_height': 0.75,
            'ground_floor_stone': True,
            'has_front_steps': True,
            'has_stairs': True,
            'stair_style': 'STRAIGHT',
            'stair_width': 1.15,
            'has_ceiling_beams': True,
            'has_front_door': True,
            'door_width': 1.35,
            'door_height': 2.50,
            'door_angle': 20.0,
            'has_windows': True,
            'has_shutters': True,


            'has_timber_framing': True,
            'timber_diagonals': True,
            'roof_style': 'GABLE',
            'roof_height': 4.0,
            'roof_overhang': 0.65,
            'has_roof_shingles': True,
            'shingle_rows': 8,
            'has_dormers': True,
            'has_chimney': True,
            'has_hoist_beam': False,
            'color_shingles': (0.18, 0.26, 0.38, 1.0),
            'color_wall_ext': (0.88, 0.84, 0.76, 1.0),
            'color_timber': (0.22, 0.13, 0.08, 1.0),
            'window_glow_strength': 3.0
        }
    },
}

BUILDING_FAMILIES = [
    {
        'id': 'TOWN_HALL',
        'name': "Town Hall",
        'category': 'CIVIC',
        'plot': "40m x 40m",
        'shape': "T-Shaped",
        'icon': 'COMMUNITY',
        'tiers': [
            ('T1', 'TOWN_HALL_T1', "Tier 1: 1-Storey Rustic Assembly"),
            ('T2', 'TOWN_HALL_T2', "Tier 2: 2-Storey Civic Hall"),
            ('T3', 'TOWN_HALL_T3', "Tier 3: 3-Storey Stone Capitol"),
        ]
    },
    {
        'id': 'WAREHOUSE',
        'name': "Warehouse",
        'category': 'INDUSTRIAL',
        'plot': "20m x 20m",
        'shape': "L-Shaped",
        'icon': 'MOD_BUILD',
        'tiers': [
            ('T1', 'WAREHOUSE_T1', "Tier 1: Open Timber Post & Roof"),
            ('T2', 'WAREHOUSE_T2', "Tier 2: Walled Depot + Crane"),
            ('T3', 'WAREHOUSE_T3', "Tier 3: Large Storehouse + Crane"),
        ]
    },
    {
        'id': 'LUMBERMILL',
        'name': "Lumbermill",
        'category': 'INDUSTRIAL',
        'plot': "20m x 20m",
        'shape': "L-Shaped",
        'icon': 'OUTLINER_OB_MESH',
        'tiers': [
            ('T1', 'LUMBERMILL_T1', "Tier 1: Open Saw Pavilion + Log Yard"),
            ('T2', 'LUMBERMILL_T2', "Tier 2: Expanded Open Mill + Skidway"),
            ('T3', 'LUMBERMILL_T3', "Tier 3: Heavy Open Timber Facility"),
        ]
    },
    {
        'id': 'INFANTRY_BARRACKS',
        'name': "Infantry Barracks",
        'category': 'MILITARY',
        'plot': "40m x 40m",
        'shape': "U-Shaped",
        'icon': 'SHIELD',
        'tiers': [
            ('T1', 'INFANTRY_BARRACKS_T1', "Tier 1: Garrison Camp & Courtyard"),
            ('T2', 'INFANTRY_BARRACKS_T2', "Tier 2: 2-Storey Garrison Base"),
            ('T3', 'INFANTRY_BARRACKS_T3', "Tier 3: Fortified Citadel Garrison"),
        ]
    },
    {
        'id': 'HOUSE_1_SMALL',
        'name': "House 1 Small",
        'category': 'RESIDENTIAL',
        'plot': "12m x 12m",
        'shape': "Square",
        'icon': 'HOME',
        'tiers': [
            ('T1', 'HOUSE_1_SMALL_T1', "Tier 1: Rustic Square Cottage"),
            ('T2', 'HOUSE_1_SMALL_T2', "Tier 2: Half-Timbered Town Cottage"),
            ('T3', 'HOUSE_1_SMALL_T3', "Tier 3: Stone Plinth Residence"),
        ]
    },
    {
        'id': 'HOUSE_2_SMALL',
        'name': "House 2 Small",
        'category': 'RESIDENTIAL',
        'plot': "12m x 12m",
        'shape': "Square (Fairytale)",
        'icon': 'LIGHT_SUN',
        'tiers': [
            ('T1', 'HOUSE_2_SMALL_T1', "Tier 1: Sway-Roof Forest Cottage"),
            ('T2', 'HOUSE_2_SMALL_T2', "Tier 2: Terracotta Sway Home"),
            ('T3', 'HOUSE_2_SMALL_T3', "Tier 3: Fantasy Slate Villa"),
        ]
    },
    {
        'id': 'HOUSE_1_MEDIUM',
        'name': "House 1 Medium",
        'category': 'RESIDENTIAL',
        'plot': "20m x 20m",
        'shape': "Square",
        'icon': 'HOME',
        'tiers': [
            ('T1', 'HOUSE_1_MEDIUM_T1', "Tier 1: Rustic Manor Lodge"),
            ('T2', 'HOUSE_1_MEDIUM_T2', "Tier 2: 2-Storey Manor Home"),
            ('T3', 'HOUSE_1_MEDIUM_T3', "Tier 3: 3-Storey Noble Estate"),
        ]
    },
    {
        'id': 'HOUSE_2_MEDIUM',
        'name': "House 2 Medium",
        'category': 'RESIDENTIAL',
        'plot': "12m x 20m",
        'shape': "Rectangular Narrow",
        'icon': 'FILE_TEXT',
        'tiers': [
            ('T1', 'HOUSE_2_MEDIUM_T1', "Tier 1: Timber Longhouse"),
            ('T2', 'HOUSE_2_MEDIUM_T2', "Tier 2: 2-Storey Narrow Townhouse"),
            ('T3', 'HOUSE_2_MEDIUM_T3', "Tier 3: 3-Storey Guildhouse"),
        ]
    },
    {
        'id': 'HOUSE_3_MEDIUM',
        'name': "House 3 Medium",
        'category': 'RESIDENTIAL',
        'plot': "20m x 20m (10m cutout)",
        'shape': "L-Shaped",
        'icon': 'SNAP_VOLUME',
        'tiers': [
            ('T1', 'HOUSE_3_MEDIUM_T1', "Tier 1: Courtyard Homestead"),
            ('T2', 'HOUSE_3_MEDIUM_T2', "Tier 2: L-Manor Residence"),
            ('T3', 'HOUSE_3_MEDIUM_T3', "Tier 3: Grand L-Estate"),
        ]
    },
]

ARCHETYPE_MAP = {
    'WAREHOUSE_T1': 'WAREHOUSE',
    'WAREHOUSE_T2': 'WAREHOUSE',
    'WAREHOUSE_T3': 'WAREHOUSE',
    'LUMBERMILL_T1': 'LUMBERMILL',
    'LUMBERMILL_T2': 'LUMBERMILL',
    'LUMBERMILL_T3': 'LUMBERMILL',
}

def apply_preset(props, preset_key):
    """Applies preset dictionary values to the PropertyGroup."""
    if preset_key not in PRESETS:
        return
        
    data = PRESETS[preset_key]['settings']
    # Temporarily disable auto_update during batch assignment to avoid multiple regenerations
    old_auto = props.auto_update
    props.auto_update = False
    
    # Assign archetype
    arch = ARCHETYPE_MAP.get(preset_key, 'NONE')
    if hasattr(props, 'building_archetype'):
        props.building_archetype = arch
        
    for k, v in data.items():
        if hasattr(props, k):
            setattr(props, k, v)
            
    props.auto_update = old_auto
    
    # Trigger final regeneration
    if old_auto:
        from .generator.building import generate_building
        import bpy
        context = bpy.context
        obj = context.active_object
        if obj and obj.get("is_fantasy_building", False):
            generate_building(obj, props)
